#!/usr/bin/env python3
"""Mutation checks: break each key protection on purpose, in a copy of the
kit, and make sure the tests notice. A mutant the tests don't kill means a
protection has no test watching it.

    python3 tests/mutate.py            # all mutants
    python3 tests/mutate.py skew       # the ones whose name contains "skew"
"""
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.dirname(HERE)

# (name, file, original text, mutated text, test modules that must fail)
MUTANTS = [
    ("sig: timestamp skew not checked", "lib/o1auth.py",
     "if abs(now - ts) > self.skew:", "if False:", ["test_gateway"]),
    ("sig: nonce replay not checked", "lib/o1auth.py",
     'if not self.nonces.check_and_add(dev_id + ":" + pre["nonce"], self.clock()):', "if False:", ["test_gateway"]),
    ("sig: signature not verified", "lib/o1auth.py",
     'if not ed25519_verify(dev["public_key"], msg, pre["sig"]):', "if False:", ["test_gateway", "test_vectors"]),
    ("sig: unpaired device accepted", "lib/o1auth.py",
     "dev = self.devices().get(dev_id)",
     "dev = self.devices().get(dev_id) or next(iter(self.devices().values()), None)", ["test_gateway"]),
    ("sig: body not covered", "lib/o1auth.py",
     '"ollama1-req-v1", method.upper(), path, body_sha_hex,', '"ollama1-req-v1", method.upper(), path, "",',
     ["test_gateway", "test_vectors"]),
    ("sig: pre-restart signatures accepted", "lib/o1auth.py",
     "if ts < self.start_time:", "if False:", ["test_gateway"]),
    ("jwt: signature not verified", "lib/o1jwt.py",
     "if not rsa_pkcs1_sha256_verify(", "if False and not rsa_pkcs1_sha256_verify(", ["test_gateway", "test_jwt"]),
    ("jwt: audience not checked", "lib/o1jwt.py",
     "if not any(isinstance(a, str) and hmac.compare_digest(a, self.aud) for a in auds):", "if False:",
     ["test_gateway", "test_jwt"]),
    ("jwt: issuer not checked", "lib/o1jwt.py", "if payload.get(\"iss\") != self.issuer:", "if False:",
     ["test_gateway"]),
    ("jwt: expiry not checked", "lib/o1jwt.py", "now > exp + LEEWAY", "now > exp + 10**9",
     ["test_gateway", "test_jwt"]),
    ("jwt: not-before not checked", "lib/o1jwt.py", "now + LEEWAY < nbf", "False", ["test_gateway"]),
    ("jwt: http certs URL allowed", "lib/o1jwt.py", 'if not url.startswith("https://") and not allow_insecure:',
     "if False:", ["test_jwt"]),
    ("gateway: service token not pinned", "bin/ollama1-gateway",
     'if want and claims.get("common_name") != want:', "if False:", ["test_gateway"]),
    ("gateway: host not checked", "bin/ollama1-gateway",
     'if host != self.cfg["hostname_gateway"].lower():', "if False:", ["test_gateway"]),
    ("gateway: LAN listener open when LAN mode is off", "bin/ollama1-gateway",
     'if not self.cfg.get("lan_mode"):', "if False:", ["test_gateway"]),
    ("gateway: LAN listener open to any address", "bin/ollama1-gateway",
     "if self.lan_net is None or ipaddress.ip_address(client_ip) not in self.lan_net:", "if False:", ["test_gateway"]),
    ("gateway: LAN listener open when no LAN range is set", "bin/ollama1-gateway",
     "if self.lan_net is None or ipaddress.ip_address(client_ip) not in self.lan_net:",
     "if self.lan_net is not None and ipaddress.ip_address(client_ip) not in self.lan_net:", ["test_gateway"]),
    ("gpu: fit estimate ignored", "bin/ollama1-gateway", "            if need <= budget:\n                return c",
     "            if True:\n                return c", ["test_gateway"]),
    ("gpu: CPU spill not refused", "bin/ollama1-gateway", "if share < 1.0:", "if False:", ["test_gateway"]),
    ("gpu: load options passed through", "bin/ollama1-gateway",
     "clean = {k: v for k, v in opts.items() if k in SAMPLING_OPTIONS}", "clean = dict(opts)", ["test_gateway"]),
    ("gpu: cloud models allowed", "lib/o1ollama.py",
     'if entry.get("remote_model") or entry.get("remote_host"):', "if False:", ["test_gateway"]),
    ("pair: wrong-code limit gone", "lib/o1pair.py", "        if left <= 0:", "        if False:", ["test_gateway"]),
    ("pair: rate limit gone", "bin/ollama1-gateway",
     'if now - gw.pair["last_try"] < PAIR_MIN_INTERVAL:', "if False:", ["test_gateway"]),
    ("pair: window reusable after a success", "lib/o1pair.py",
     '    close_window(w["id"])  # one success closes the window', "    pass", ["test_gateway"]),
    ("pair: root step skips the code", "lib/o1pair.py",
     'if not check_pair_mac(w["code"], name, pub_b64, ts, nonce, mac):', "if False:", ["test_gateway"]),
    ("pair: nonce reuse accepted", "lib/o1pair.py", 'if nonce in w.get("nonces", []):', "if False:",
     ["test_gateway"]),
    ("pair: window never expires", [
        ("lib/o1pair.py", 'if float(w["expires_at"]) <= now or not w["id"] or not w["code"]:', "if False:"),
        ("lib/o1pair.py", 'and w["expires_at"] > now:', ":")], ["test_gateway"]),
    ("pair: allowed on the LAN listener", "bin/ollama1-gateway",
     '            if lan:\n                raise GatewayError(403, "pair_closed"',
     '            if False:\n                raise GatewayError(403, "pair_closed"', ["test_gateway"]),
    ("F1: gateway errors keep the connection open", "bin/ollama1-gateway",
     '                self.send_header("Connection", "close")\n                self.close_connection = True\n',
     "                pass\n", ["test_gateway"]),
    ("F1: panel errors keep the connection open", "bin/ollama1-admin",
     '                self.send_header("Connection", "close")\n                self.close_connection = True\n',
     "                pass\n", ["test_admin"]),
    ("F3: body read before the signature headers", "bin/ollama1-gateway",
     "                    pre = gw.verifier.precheck(method, self.path, self.headers)\n"
     "                    body = self.read_body(max_body)\n",
     "                    body = self.read_body(max_body)\n"
     "                    pre = gw.verifier.precheck(method, self.path, self.headers)\n", ["test_gateway"]),
    ("F3: no cap on requests in flight", "bin/ollama1-gateway",
     "if not gw.inflight.acquire(blocking=False):", "if False:", ["test_gateway"]),
    ("F5: exception mid-stream breaks the stream", "bin/ollama1-gateway",
     "            except Exception as e:\n                # e.g. Ollama restarting",
     "            except ZeroDivisionError as e:\n                # e.g. Ollama restarting", ["test_gateway"]),
    ("KV: models kept across devices", "bin/ollama1-gateway",
     "if self.last_device is None or self.last_device == dev_id:", "if True:", ["test_gateway"]),
    ("dash: pairing code drawn blank", "lib/o1big.py", "for c in g[i])", "for c in g)", ["test_big"]),
    ("ram: flagged models held to VRAM", "bin/ollama1-gateway",
     "        if not ram:\n            return self.ensure_on_gpu(name)", "        if True:\n            return self.ensure_on_gpu(name)",
     ["test_gateway"]),
    ("ram: every model may use RAM", "bin/ollama1-gateway", "            ram = gw.is_ram_model(name)",
     "            ram = True", ["test_gateway"]),
    ("ram: swap not checked", "bin/ollama1-gateway",
     "if swapped > (512 << 20) or int(after.get(\"MemAvailable\", 1 << 40)) < (1 << 30):", "if False:",
     ["test_gateway"]),
    ("ram: loads next to other models", "bin/ollama1-gateway", "        if not victims:\n            return",
     "        if True:\n            return", ["test_gateway"]),
    ("ram: no context step-down", "bin/ollama1-gateway", "            tries += [c for c in (4096, 2048) if c < n_ctx]",
     "            pass", ["test_gateway"]),
    ("allow: unknown flags accepted", "lib/o1common.py", "        elif any(fl not in ALLOW_FLAGS for fl in flags):",
     "        elif False:", ["test_gateway"]),
    ("access: 'none' mode on by default", "bin/ollama1-gateway", '        if self.cfg.get("access") == "none":',
     '        if self.cfg.get("access") != "cloudflare_only":', ["test_gateway"]),
    ("none: any Host accepted", "bin/ollama1-gateway",
     'if not re.match(r"^(127\\.0\\.0\\.1|localhost)(:[0-9]{1,5})?$", host):', "if False:", ["test_gateway"]),
    ("none: Origin accepted", "bin/ollama1-gateway", '            if headers.get("Origin") is not None:',
     "            if False:", ["test_gateway"]),
    ("none: non-JSON POST accepted", "bin/ollama1-gateway", '            if method == "POST" and (headers.get',
     '            if False and (headers.get', ["test_gateway"]),
    ("none: starts next to a tunnel", "bin/ollama1-gateway",
     '    if cfg.get("access") == "none" and cfg.get("tunnel_id"):', "    if False:", ["test_gateway"]),
    ("ram: spilled model kept next to a GPU-only job", "bin/ollama1-gateway",
     'return self.is_ram_model(n) or int(m.get("size_vram") or 0) < int(m.get("size") or 0)',
     "return self.is_ram_model(n)", ["test_gateway"]),
    ("mem: mmap left on for ram models", "bin/ollama1-gateway", '            clean["use_mmap"] = False',
     "            pass", ["test_gateway"]),
    ("mem: warm load with mmap", "bin/ollama1-gateway", '            opts["use_mmap"] = False   # see shape()',
     "            pass", ["test_gateway"]),
    ("mem: margin 6 GiB again", "bin/ollama1-gateway",
     'margin = max(8 << 30, int(mi.get("MemTotal", 0) * 0.12), int(self.cfg.get("ram_margin_gib") or 8) << 30)',
     "margin = 6 << 30", ["test_gateway"]),
    ("mem: Ollama's cap ignored", "bin/ollama1-gateway", "        if high:\n", "        if False:\n",
     ["test_gateway"]),
    ("mem: compute buffers not counted", "lib/o1ollama.py",
     "(RAM_COMPUTE_BYTES if ram else (256 << 20))", "(256 << 20)", ["test_gateway"]),
    ("mem: OOM not reported", "bin/ollama1-gateway",
     "        if before is not None and after is not None and after > before:", "        if False:",
     ["test_gateway"]),
    ("mem: Ollama dying taken for the client leaving", "bin/ollama1-gateway",
     '        except OSError:\n            raise GatewayError(502, "ollama", "Ollama stopped while loading the model")',
     '        except ZeroDivisionError:\n            raise GatewayError(502, "ollama", "Ollama stopped while loading the model")',
     ["test_gateway"]),
    ("repack: VRAM counted while repacking is on", "bin/ollama1-gateway",
     '        host_only = ram and not self.cfg.get("ollama_no_repack")', "        host_only = False", ["test_gateway"]),
    ("repack: mmap forced off with repacking off", "bin/ollama1-gateway",
     '        if ram and not self.cfg.get("ollama_no_repack"):\n            # With repacking on',
     '        if ram:\n            # With repacking on', ["test_gateway"]),
    ("info: every detected field served", "bin/ollama1-gateway",
     '                return self.send_json(200, {"gpu": {"vendor": g.get("vendor"), "name": g.get("name"),\n'
     '                                                    "vram_bytes": g.get("vram_bytes")}})',
     '                return self.send_json(200, {"gpu": dict(g)})', ["test_gateway"]),
    ("info: a missing card is never looked for again", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if False:', ["test_gateway"]),
    ("info: a missing card is looked for on every request", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if not (self.gpu_info or {}).get("vendor"):', ["test_gateway"]),
    ("info: a found card is looked for again", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if time.monotonic() - self.gpu_at >= GPU_RECHECK_S:', ["test_gateway"]),
    ("money: panel shows more than cents", "bin/ollama1-admin",
     "(c/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})",
     "Math.abs(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4})", ["test_admin"]),
    ("money: panel sub-cent shown as $0.00", "bin/ollama1-admin",
     "if(v>0&&c===0)return '<'+sym+'0.01';", "", ["test_admin"]),
    ("money: panel per-token back to per 1,000", "bin/ollama1-admin",
     "'Cost per 1 million tokens: '+money(m.cost_per_1k_tokens*1000,sym)", "'Cost per 1,000 tokens: '+money(m.cost_per_1k_tokens,sym)", ["test_admin"]),
    ("money: cli shows more than cents", "bin/ollama1-power",
     'return "%s%s" % (sym, format(v, ",.2f"))', 'return "%s%s" % (sym, format(v, ",.4f"))', ["test_power"]),
    ("money: cli sub-cent shown as $0.00", "bin/ollama1-power",
     '    if v > 0 and round(v, 2) == 0:\n        return "<%s0.01" % sym\n', "", ["test_power"]),
    ("info: revision table ignored", "lib/o1gpu.py", "        name = AMD_BY_REVISION.get(key)", "        name = None",
     ["test_gpu"]),
    ("sleep: helper ignores busy work", "bin/ollama1-helper", "    reasons = o1sleep.busy_reasons()\n    if reasons:",
     "    reasons = o1sleep.busy_reasons()\n    if False:", ["test_sleep"]),
    ("sleep: panel ignores busy work", "bin/ollama1-admin", "                if reasons:\n                    return 409",
     "                if False:\n                    return 409", ["test_admin"]),
    ("sleep: busy units not matched", "lib/o1sleep.py", "        if any(fnmatch.fnmatchcase(u, pattern) for u in active):",
     "        if False:", ["test_sleep"]),
    ("sleep: setup lock ignored", "lib/o1sleep.py", '    if setup_running(setup_lock):', "    if False:",
     ["test_sleep"]),
    ("sleep: no restart after a bad wake", "lib/o1sleep.py",
     '        restart(["ollama.service", "ollama1-tunnel.service"])', "        pass", ["test_sleep"]),
    ("dash: ASCII mode lets glyphs through", "lib/o1dashui.py", '    if glyphs == "ascii":\n        return "".join(ASCII_MAP',
     '    if False:\n        return "".join(ASCII_MAP', ["test_dash"]),
    ("dash: console draws glyphs its font lacks", "lib/o1dashui.py", "    if console:\n        return", "    if False:\n        return",
     ["test_dash"]),
    ("dash: pairing overlay not full screen", "lib/o1dashui.py",
     '    c.fill(0, 0, c.w, c.h, " ", "overlay")', "    pass", ["test_dash"]),
    ("dash: a widget can write outside its box", "lib/o1dashui.py", "            elif 0 <= x < self.w:", "            elif 0 <= x:",
     ["test_dash"]),
    ("dash: a box's row is not clipped to the row", "lib/o1dashui.py", "        if y < 0 or y >= self.h:\n            return\n        text = fold",
     "        text = fold", ["test_dash"]),
    ("dash: a box is blitted past the frame", "lib/o1dashui.py", "                if not 0 <= tx < self.w:\n                    continue\n                ch, st",
     "                ch, st", ["test_dash"]),
    ("dash: ANSI codes counted in the width", "lib/o1dashui.py", "    return sum(cw(c) for c in strip_ansi(str(s)))",
     "    return sum(cw(c) for c in str(s))", ["test_dash"]),
    ("dash: text is not cut to its width", "lib/o1dashui.py", "    if swidth(s) <= w:\n        return s", "    if True:\n        return s",
     ["test_dash"]),
    ("dash: put does not cut to maxw", "lib/o1dashui.py", "        if maxw is not None:\n            text = trunc(text, maxw)", "        pass",
     ["test_dash"]),
    ("dash: wide characters take one cell", "lib/o1dashui.py", '    return 2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1',
     "    return 1", ["test_dash"]),
    ("dash: escape sequences in names reach the screen", "lib/o1dashui.py", "    s = strip_ansi(str(s)).replace",
     "    s = str(s).replace", ["test_dash"]),
    ("dash: control characters reach the screen", "lib/o1dashui.py", '    return CTRL_RE.sub("", s)', "    return s", ["test_dash"]),
    ("dash: panels overlap", "lib/o1dashui.py", "        y += rh + gap\n", "        y += rh + gap - 1\n", ["test_dash"]),
    ("dash: panels run off a short screen", "lib/o1dashui.py", "        if used + rh > body:\n            break", "        if False:\n            break",
     ["test_dash"]),
    ("dash: a wide screen is stretched, not centred", "lib/o1dashui.py", "    cw_ = min(w, MAX_W)", "    cw_ = w", ["test_dash"]),
    ("dash: a failing widget blanks the screen", "lib/o1dashui.py", "        except Exception as e:", "        except ZeroDivisionError as e:",
     ["test_dash"]),
    ("dash: a resize does not clear the screen", "lib/o1dashterm.py", "full = size != self.size or self.rows is None",
     "full = self.rows is None", ["test_dash"]),
    ("dash: the screen is never fully redrawn", "lib/o1dashterm.py", "        elif now - self.last_full >= self.refresh_s:",
     "        elif False:", ["test_dash"]),
    ("dash: line wrap left on", "lib/o1dashterm.py", r'MODES = "\x1b[?7l\x1b[?25l"', r'MODES = "\x1b[?25l"', ["test_dash"]),
    ("dash: rows not at absolute positions", "lib/o1dashterm.py", r'"\x1b[%d;1H%s" % (y + 1, r)', r'"\n%s" % r', ["test_dash"]),
    ("dash: the size is not asked for", "lib/o1dashterm.py", "            sz = os.get_terminal_size(fd)", "            raise OSError",
     ["test_dash"]),
    ("dash: the program keeps its first size", "bin/ollama1-dash", "size = o1dashterm.term_size()", "size = (100, 30)",
     ["test_dash"]),
    ("dash: font without blocks picked as blocks", "lib/o1font.py",
     '    return "blocks" if all(ord(c) in cps for c in NEEDED["blocks"]) else "ascii"', '    return "blocks"', ["test_dash"]),
    ("dash: the small console font is kept", "lib/o1font.py", "TARGET_COLS = 120", "TARGET_COLS = 240", ["test_dash"]),
    ("dash: the font opt-out is ignored", "lib/o1font.py", "    choice = None if os.path.exists(off_flag) else pick(",
     "    choice = pick(", ["test_dash"]),
    ("setup: the console font opt-out installs anyway", "lib/setuplib.sh", '  if [ "${OLLAMA1_DASH_FONT:-on}" = off ]; then',
     "  if false; then", ["test_setuplib"]),
    ("setup: a failed console font stops setup", "lib/setuplib.sh", '    note "couldn\'t load a console font', '    die "couldn\'t load a console font',
     ["test_setuplib"]),
    ("panel: a pixmap clip is ignored", "lib/o1gfx.py", "        xa, xb = max(x, x0), min(x + w, x1)",
     "        xa, xb = max(x, 0), min(x + w, self.w)", ["test_panel"]),
    ("panel: a panel's box does not clip it", "lib/o1panel.py", "        with pm.clipped(*r):", "        if True:", ["test_panel"]),
    ("panel: text is not cut to its width", "lib/o1pixfont.py", "    if text_width(text, scale) <= max_w:\n        return text",
     "    if True:\n        return text", ["test_panel"]),
    ("panel: a frame lets widgets onto its border", "lib/o1panel.py", "    pm.clip = (max(c[0], inner[0]),",
     "    pm.clip = (max(c[0], x),", ["test_panel"]),
    ("panel: the stride is ignored", "lib/o1fb.py", "return self.base + screen_row * self.info.line_length + self.ox * self.bpp",
     "return self.base + screen_row * self.info.xres * self.bpp + self.ox * self.bpp", ["test_panel"]),
    ("panel: unchanged rows are written again", "lib/o1fb.py", "            if not force and self.prev[y] == raw:",
     "            if False:", ["test_panel"]),
    ("panel: colour channels not shifted into place", "lib/o1fb.py", "        return (v >> (8 - min(8, ln))) << off",
     "        return v << off", ["test_panel"]),
    ("panel: a disconnected monitor counts", "lib/o1fb.py", '                if f.read(32).strip() == "connected":',
     '                if f.read(32).strip():', ["test_panel"]),
    ("panel: the console is left in graphics mode", "lib/o1paneld.py", "        tty.leave()", "        pass", ["test_panel"]),
    ("panel: the text dashboard is not the fall-back", "bin/ollama1-dash", "                failed[0] = True", "                raise",
     ["test_panel"]),
    ("dash: partitions counted twice", "lib/o1metrics.py",
     'DISK_RE = re.compile(r"^(nvme\\d+n\\d+|sd[a-z]+|vd[a-z]+|hd[a-z]+)$")',
     'DISK_RE = re.compile(r"^(nvme\\d+n\\d+\\S*|sd[a-z]+\\d*|vd[a-z]+|hd[a-z]+)$")', ["test_dash"]),
    ("dash: idle time ignored", "lib/o1metrics.py", "        idle = vals[3] + (vals[4] if len(vals) > 4 else 0)",
     "        idle = 0", ["test_dash"]),
    ("setup: no mkfs after a crash before it", "lib/setuplib.sh",
     "    run mkfs.ext4 -F -q -L o1data", "    true && : mkfs.ext4 -F -q -L o1data", ["test_setuplib"]),
    ("setup: array mkfs without setup's marker", "lib/setuplib.sh",
     '    [ -f "$STATE_DIR/raid.mkfs-pending" ] || fsck_hint', "    true || fsck_hint", ["test_setuplib"]),
    ("setup: models mkfs without setup's marker", "lib/setuplib.sh",
     '    [ -f "$STATE_DIR/models.mkfs-pending" ] || fsck_hint', "    true || fsck_hint", ["test_setuplib"]),
    ("setup: blkid read errors ignored", "lib/setuplib.sh",
     '    *) echo "blkid could not read $1 (exit $rc)" >&2; return 3 ;;', "    *) ;;", ["test_setuplib"]),
    ("KV: device switch fails open", "bin/ollama1-gateway", "        if not cleared:", "        if False:",
     ["test_gateway"]),
    ("cf: foreign CNAME changed", "bin/ollama1-cf-access", "        if foreign:", "        if False:",
     ["test_cloudflare"]),
    ("cf: redirects followed", "bin/ollama1-cf-access", "OPENER = urllib.request.build_opener(NoRedirect)",
     "OPENER = urllib.request.build_opener()", ["test_cloudflare"]),
    ("cf: new secret shown only at the end", "bin/ollama1-cf-access",
     '        say("created service token %s (never expires)" % TOKEN_NAME)\n'
     '        if show_secret(tok["client_id"], tok.get("client_secret"), test_mode):',
     '        say("created service token %s (never expires)" % TOKEN_NAME)\n'
     '        if False:', ["test_cloudflare"]),
    ("cf: unshown secret not replaced", "bin/ollama1-cf-access",
     "            rotate = True\n        if rotate is None:", "            pass\n        if rotate is None:",
     ["test_cloudflare"]),
    ("cf: service token expires in a year", "bin/ollama1-cf-access", '"duration": "forever"',
     '"duration": "8760h"', ["test_cloudflare"]),
    ("setup: a mirror on the disks is wiped again", "lib/setuplib.sh",
     '      [ -n "$line" ] && md_line_is_ours "$line" && echo "$dev"', "      true", ["test_setuplib"]),
    ("setup: fstab line without a UUID", [
        ("lib/setuplib.sh", '  [[ "$line" =~ ^UUID=[0-9A-Fa-f-]{8,}[[:space:]] ]] || die', "  true || die"),
        ("lib/setuplib.sh", '  [ -n "$uuid" ] || die "no filesystem UUID on $md; fstab left as it was"', "  true")],
     ["test_setuplib"]),
    ("setup: unparseable free space accepted", "lib/setuplib.sh",
     "  case \"$n\" in ''|*[!0-9]*) return 1 ;; esac", "  true", ["test_setuplib"]),
    ("setup: unexpected signature wiped", "lib/setuplib.sh",
     """    case " $* " in *" $t "*) ;; *) echo "$dev carries '$t'"; bad=1 ;; esac""",
     """    case " $* " in *) ;; esac""", ["test_setuplib"]),
    ("setup: fstab/crypttab/swap users ignored", "lib/setuplib.sh", "  return $found", "  return 1",
     ["test_setuplib"]),
    ("setup: wrong serial wiped", "lib/setuplib.sh",
     '    serial_is "$d2" "$s2" || die', '    true || die', ["test_setuplib"]),
    ("stateless: request body written to disk", "bin/ollama1-gateway",
     "            name, entry = gw.local_model(obj.get(\"model\"))\n",
     "            name, entry = gw.local_model(obj.get(\"model\"))\n"
     "            open(os.path.join(Paths.gw_state, 'last.json'), 'w').write(json.dumps(obj))\n",
     ["test_stateless"]),
    ("stateless: answer logged", "bin/ollama1-gateway",
     "                    self.chunk(line)\n",
     "                    self.chunk(line)\n                    log(\"debug\", reason=line)\n",
     ["test_stateless"]),
    ("stateless: default request log back on", "bin/ollama1-gateway",
     "        def log_message(self, fmt, *args):  # the default logs request lines; we log our own\n            pass",
     "        def log_message(self, fmt, *args):  # the default logs request lines; we log our own\n"
     "            BaseHTTPRequestHandler.log_message(self, fmt, *args)",
     ["test_stateless"]),
    ("admin: any Access user accepted", "bin/ollama1-admin",
     "if not email or not hmac.compare_digest(email.encode(), want.encode()):", "if not email:",
     ["test_admin"]),
    ("admin: CSRF token not checked", "bin/ollama1-admin",
     "if not hmac.compare_digest(tok.encode(), self.csrf(email).encode()):", "if False:", ["test_admin"]),
    ("admin: Origin not checked", "bin/ollama1-admin",
     'if (headers.get("Origin") or "").lower() != self.origin:', "if False:", ["test_admin"]),
    ("admin: pull beyond the allow-list", "bin/ollama1-admin", "if arg not in allowed:", "if False:",
     ["test_admin"]),
    ("admin: reboot without confirmation", "bin/ollama1-admin",
     'if act == "reboot" and obj.get("confirm") != "reboot":', "if False:", ["test_admin"]),
    ("updater: checksum ignored", "bin/ollama1-update-ollama", "if got != want:", "if False:", ["test_updater"]),
    ("updater: GitHub digest ignored", "bin/ollama1-update-ollama",
     'if gh and gh != "sha256:" + want:', "if False:", ["test_updater"]),
    ("updater: archive paths trusted", "bin/ollama1-update-ollama",
     'tf.extractall(dest, filter="data")', 'tf.extractall(dest, filter="fully_trusted")', ["test_updater"]),
    ("updater: missing checksum line accepted", "bin/ollama1-update-ollama",
     "            if not want:\n", "            if False:\n", ["test_updater"]),
    ("cf: duplicate CNAMEs kept", "bin/ollama1-cf-access", "        for r in extra:", "        for r in []:",
     ["test_cloudflare"]),
    ("cf: a new CNAME on every run", "bin/ollama1-cf-access", "        if not cnames:", "        if True:",
     ["test_cloudflare"]),
    ("cf: API token saved to disk", "bin/ollama1-cf-access", "    del token\n",
     "    open(os.path.join(Paths.etc, 'cf-token'), 'w').write(token)\n    del token\n", ["test_cloudflare"]),
    ("cf: tunnel credential readable by all", "bin/ollama1-cf-access",
     "write_json_atomic(creds_path, creds, mode=0o600)", "write_json_atomic(creds_path, creds, mode=0o644)",
     ["test_cloudflare"]),
    ("cf: a new tunnel on every run", "bin/ollama1-cf-access", "    if found:\n", "    if False:\n",
     ["test_cloudflare"]),
    ("library: listed models removed", "lib/o1library.py",
     '        if not kept(m["name"], allowed, protected):', "        if True:", ["test_library"]),
    ("library: removal not re-checked at sync time", "lib/o1library.py",
     "        if list_broken or kept(name, allowed, protected):   # back on the list (or a bad line names it): keep it",
     "        if False:",
     ["test_library"]),
    ("library: delisted model still fetched", "lib/o1library.py",
     '        if listed(item["name"], allowed):', "        if True:", ["test_library"]),
    ("library: update check inverted", "lib/o1library.py",
     'elif str(local.get("digest") or "").replace("sha256:", "") != digest:',
     'elif str(local.get("digest") or "").replace("sha256:", "") == digest:', ["test_library"]),
    ("library: sizes count layers already on disk", "lib/o1library.py",
     "if not have_blob(d))", "if True)", ["test_library"]),
    ("library: only two tries", "lib/o1library.py",
     "for attempt in range(1, tries + 1):", "for attempt in range(1, tries):", ["test_library"]),
    ("library: cached layers counted as progress", "lib/o1library.py",
     'seen[d] = {"cached": done >= tot,', 'seen[d] = {"cached": False,', ["test_library"]),
    ("library: rate not smoothed", "lib/o1library.py",
     "0.85 * self.rate + 0.15 * inst", "inst", ["test_library"]),
    ("library: registry down means remove", "lib/o1library.py",
     "        if manifest is None:\n            if local is None:",
     "        if manifest is None and False:\n            if local is None:", ["test_library"]),
    ("library: bad allow-list line left behind", "lib/o1library.py",
     "        _write_allow(lines[:-1], allow_path)\n", "        pass\n", ["test_library"]),
    ("library: panel sync ignores the preview", "bin/ollama1-models",
     'if want is None or want["id"] != p["id"]:', "if False:", ["test_library"]),
    ("library: sync without typed yes", "bin/ollama1-models",
     'if ask("Type yes to do exactly this: ") != "yes":', "if False:", ["test_library"]),
    ("library: two syncs at once", "lib/o1library.py",
     "            fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)\n", "            pass\n", ["test_library"]),
    ("library: sleep ignores a CLI sync", "lib/o1sleep.py",
     "if lib_why not in reasons and setup_running(library_lock()):", "if False:", ["test_library"]),
    ("admin: library sync without the shown preview", "bin/ollama1-admin",
     'if arg != p["id"] or confirm != p["id"]:', "if False:", ["test_admin"]),
    ("admin: library sync with a stale preview", "lib/o1library.py",
     'if (now or time.time()) - int(p.get("made_at") or 0) > max_age:', "if False:", ["test_admin"]),
    ("admin: library sync without space", "bin/ollama1-admin",
     'if not p.get("enough_space", False):', "if False:", ["test_admin"]),
    ("power: weekends get on-peak", "lib/o1tariff.py",
     'if w["tier"] in ("on", "mid") and self.weekend_like(d):', "if False:", ["test_power"]),
    ("power: holidays ignored", "lib/o1tariff.py",
     'return (self.s["weekends_off_peak"] and d.weekday() >= 5) or self.holiday(d) is not None',
     'return (self.s["weekends_off_peak"] and d.weekday() >= 5)', ["test_power"]),
    ("power: holidays never observed", "lib/o1tariff.py",
     "d = _observed(d) if observed else d", "d = d", ["test_power"]),
    ("power: windows stop at midnight", "lib/o1tariff.py",
     "                elif wraps:\n                    span = range(0, e0)",
     "                elif False:\n                    span = range(0, e0)", ["test_power"]),
    ("power: last window wins, not the most specific", "lib/o1tariff.py",
     "if best[i] is None or key < best[i][0]:", "if True:", ["test_power"]),
    ("power: seasons can't wrap the new year", "lib/o1tariff.py",
     "if (a <= doy <= b) if a <= b else (doy >= a or doy <= b):", "if a <= doy <= b:", ["test_power"]),
    ("power: DST ignored in the fast path", "lib/o1tariff.py",
     "base = lt if end.utcoffset() == lt.utcoffset() else None", "base = lt", ["test_power"]),
    ("power: uncovered time on-peak", "lib/o1tariff.py",
     'm = [b[1] if b else "off" for b in best]', 'm = [b[1] if b else "on" for b in best]', ["test_power"]),
    ("power: time-of-use without prices", "lib/o1tariff.py",
     '            if out["tiers"].get(t) is None:', "            if False:", ["test_power", "test_admin"]),
    ("power: overlapping seasons accepted", "lib/o1tariff.py",
     "                if doy in owner:", "                if False:", ["test_power"]),
    ("power: energy not split at the minute", "lib/o1power.py",
     "            e = min(t1, m + 60)", "            e = t1", ["test_power"]),
    ("power: gaps counted", "lib/o1power.py",
     "            if now - t0 <= GAP_S:", "            if True:", ["test_power"]),
    ("power: sleep not counted", "lib/o1power.py",
     '        self.meter.add(max(t0, a), min(t1, b), float(self.cfg.get("power_sleep_w", 3)), "sleep")',
     "        pass", ["test_power"]),
    ("power: RAPL wrap lost", "lib/o1power.py", "    return (rng - e0) + e1 + 1", "    return 0", ["test_power"]),
    ("power: the plug ignored", "lib/o1power.py", "        if self.plug:\n            try:",
     "        if False:\n            try:", ["test_power"]),
    ("power: plug beyond the LAN", "lib/o1power.py",
     "    if not any(ip in n for n in LAN_NETS if n.version == ip.version):",
     "    if False:", ["test_power"]),
    ("power: plug redirects followed", "lib/o1power.py", "    handlers = [_NoRedirect(), _DeadlineHTTPHandler(deadline)]",
     "    handlers = [_DeadlineHTTPHandler(deadline)]",
     ["test_power"]),
    ("power: unknown time shown as none", "lib/o1power.py",
     '"unknown_h": round(max(0, span - known) / 3600.0, 2)', '"unknown_h": 0', ["test_power"]),
    ("power: one price for a whole window", "lib/o1power.py",
     "    tiers = tariff.tiers_for_minutes([r[0] for r in rows])",
     "    tiers = [tariff.tier_at(rows[0][0])] * len(rows) if rows else []", ["test_power"]),
    ("power: projection ignores the weekday", "lib/o1power.py",
     "        k = lt.weekday() * 24 + lt.hour", "        k = lt.hour", ["test_power"]),
    ("power: Kasa cipher wrong", "lib/o1power.py", "        out.append(key ^ b)\n        key = b",
     "        out.append(key ^ b)\n        key = key ^ b", ["test_power"]),
    ("power: price file readable by all", "lib/o1power.py",
     '    write_json_atomic(tariff_file(), clean, mode=0o640, group="o1view")',
     '    write_json_atomic(tariff_file(), clean, mode=0o644, group="o1view")',
     ["test_power", "test_admin", "test_rootfiles"]),
    ("admin: big bodies on every action", "bin/ollama1-admin",
     '(65536 if path == "/api/power/schedule" else 4096)', "65536", ["test_admin"]),
    ("admin: prices saved unchecked", "bin/ollama1-admin",
     "        clean, errs = o1tariff.validate(obj)\n        if errs:",
     "        clean, errs = obj, []\n        if errs:", ["test_admin"]),
    ("root files: mode set by path", "lib/o1common.py",
     "            os.fchmod(f.fileno(), mode)", "            os.chmod(tmp, mode)", ["test_rootfiles"]),
    ("root files: symlinks followed on read", "lib/o1common.py",
     "os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK", "os.O_RDONLY | os.O_NONBLOCK", ["test_rootfiles"]),
    ("root files: panel request read unsafely", "lib/o1power.py",
     "    s = read_json_safe(path, max_bytes=MAX_SCHEDULE_BYTES,\n"
     "                       check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)",
     "    s = read_json(path)", ["test_rootfiles"]),
    ("root files: tariff read unsafely", "lib/o1power.py",
     "        s = read_json_safe(tariff_file(), max_bytes=MAX_SCHEDULE_BYTES)",
     "        s = read_json(tariff_file())", ["test_rootfiles"]),
    ("root files: pairing spool read unsafely", "lib/o1pair.py",
     "        req = read_json_safe(fp, max_bytes=8192)", "        req = read_json(fp, max_bytes=8192)",
     ["test_rootfiles"]),
    ("power: IPv4-mapped addresses not unwrapped", "lib/o1power.py",
     "    if ip.version == 6 and ip.ipv4_mapped is not None:", "    if False:", ["test_power"]),
    ("power: link-local plugs allowed", "lib/o1power.py",
     '"192.168.0.0/16", "fc00::/7"))', '"192.168.0.0/16", "fc00::/7", "169.254.0.0/16"))',
     ["test_power", "test_rootfiles"]),
    ("power: Shelly Gen1 answers any auth", "lib/o1power.py",
     "        handlers.append(urllib.request.HTTPBasicAuthHandler(mgr) if auth == \"basic\"\n"
     "                        else urllib.request.HTTPDigestAuthHandler(mgr))",
     "        handlers += [urllib.request.HTTPBasicAuthHandler(mgr), urllib.request.HTTPDigestAuthHandler(mgr)]",
     ["test_power"]),
    ("power: any plug error kills the sampler", "lib/o1power.py",
     "            except Exception:\n                self.plug_state = {",
     "            except ZeroDivisionError:\n                self.plug_state = {", ["test_power"]),
    ("power: no overall plug deadline", "lib/o1power.py",
     "        left = self.deadline - time.monotonic()", "        left = PLUG_DEADLINE_S", ["test_power"]),
    ("power: plug reply shape unchecked", "lib/o1power.py",
     "    if not isinstance(v, dict):\n        raise PlugError(\"the %s reply isn't in the expected shape\" % what)",
     "    pass", ["test_power"]),
    ("library: a bad line doesn't protect its model", "lib/o1library.py",
     "    low = [p.lower() for p in protected]\n    return listed(name.lower(), low)",
     "    return False", ["test_library"]),
    ("library: removals planned despite a broken list", "lib/o1library.py",
     '            (blocked if errors else remove).append(', '            remove.append(', ["test_library"]),
    ("library: removals run despite a broken list", "lib/o1library.py",
     "        if list_broken or kept(name, allowed, protected):", "        if kept(name, allowed, protected):",
     ["test_library"]),
    ("library: no disk figure passes", "lib/o1library.py",
     '"enough_space": after is not None and after >= MIN_FREE,', '"enough_space": after is None or after >= MIN_FREE,',
     ["test_library"]),
    ("library: shared blobs counted as freed", "lib/o1library.py",
     "    return sum(s for d, s in gone.items() if d not in keep)", "    return sum(gone.values())",
     ["test_library"]),
    ("library: manifests unchecked", "lib/o1library.py",
     "    if not valid_manifest(m):\n        return None, None", "    if False:\n        return None, None",
     ["test_library"]),
    ("library: registry redirects followed", "lib/o1library.py",
     "    opener = urllib.request.build_opener(_NoRedirect())", "    opener = urllib.request.build_opener()",
     ["test_library"]),
    ("setup-safety: RAM part above MemoryHigh", "bin/ollama1-gateway",
     "            ram_part = min(ram_part, high)", "            ram_part = min(ram_part, cap - (1 << 30)) if cap else ram_part",
     ["test_gateway"]),
    ("setup-safety: inhibitor never let go", "lib/o1sleep.py",
     "                os.killpg(self.p.pid, signal.SIGTERM)", "                pass", ["test_sleep"]),
    ("setup-safety: RAM test ignores a hangup", "tools/ram_model_test.py",
     "    raise SystemExit(128 + signum)", "    return None", ["test_tools"]),
    ("setup-safety: RAM test signals not caught", "tools/ram_model_test.py",
     "        signal.signal(sig, exit_on_signal)", "        pass", ["test_tools"]),
    ("setup-safety: swap off carries on after a failed swapoff", "tools/encrypted-swap.sh",
     '    swapoff "$MAPPER" || die "swapoff $MAPPER failed (not enough free memory to take its pages back?). Nothing was changed; free some memory and try again."',
     '    swapoff "$MAPPER" || true', ["test_tools"]),
    ("setup-safety: swap volume without room", "tools/encrypted-swap.sh",
     '    [ "$free" -ge "$need" ] || die', '    true || die', ["test_tools"]),
    ("setup-safety: swap may hold up the boot", "tools/encrypted-swap.sh",
     "swap,cipher=aes-xts-plain64,size=512,nofail", "swap,cipher=aes-xts-plain64,size=512", ["test_tools"]),
    ("setup-safety: swap not finished on a re-run", "tools/encrypted-swap.sh",
     "  if lv_exists; then\n    echo \"volume $LVDEV: already there\"",
     "  if false; then\n    echo \"volume $LVDEV: already there\"", ["test_tools"]),
    ("setup-safety: swap back in the default RAM test", "tools/ram_model_test.py",
     'DEFAULT_CONFIGS = ["norepack", "norepack-moe"]', 'DEFAULT_CONFIGS = ["norepack", "norepack-moe", "swap"]',
     ["test_tools"]),
    ("setup-safety: swap config runs without the encrypted swap", "tools/ram_model_test.py",
     '    if "swap" not in names or swap_bytes:\n        return None', '    if True:\n        return None',
     ["test_tools"]),
    ("setup-safety: VG reserve not rounded up", "lib/setuplib.sh",
     "  echo $(( (${1:-0} * 1073741824 + e - 1) / e ))", "  echo $(( ${1:-0} * 1073741824 / e ))",
     ["test_setuplib"]),
    ("lows: request owner not checked", "lib/o1power.py",
     "check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)", "check=lambda st: st.st_nlink == 1)",
     ["test_rootfiles"]),
    ("lows: hard-linked request trusted", "lib/o1power.py",
     "check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)", "check=lambda st: st.st_uid == owner_uid)",
     ["test_rootfiles"]),
    ("lows: validation echoes an input key", "lib/o1tariff.py",
     '(k if re.match(r"^[a-z_]{1,30}$", str(k)) else "(unreadable name)")', "k", ["test_rootfiles"]),
    ("lows: missing allow-list reads as empty and clean", "lib/o1common.py",
     '        errors.append({"line": 0, "text": "", "reason": "models.allow is missing or can\'t be read"})\n',
     "", ["test_library"]),
    ("lows: freed counted despite an unreadable kept manifest", "lib/o1library.py",
     "            if not isinstance(m, dict):\n                return 0", "            if not isinstance(m, dict):\n                continue",
     ["test_library"]),
    ("lows: CLI inhibitor outlives a killed job", "lib/o1sleep.py",
     '"--why=" + self.why, "sh", "-c", "cat >/dev/null"]', '"--why=" + self.why, "sh", "-c", "sleep 600"]',
     ["test_sleep"]),
    ("lows: setup inhibitor outlives setup", "lib/setuplib.sh",
     "sh -c 'while kill -0 \"$1\" 2>/dev/null; do sleep 2; done'", "sh -c 'while true; do sleep 2; done'",
     ["test_sleep"]),
    ("lows: swap off removes a volume it didn't make", "tools/encrypted-swap.sh",
     "  if state_has lv_created && lv_exists; then", "  if lv_exists; then", ["test_tools"]),
    ("lows: RAM test output can stop the cleanup", "tools/ram_model_test.py",
     "    except (OSError, ValueError):    # BrokenPipeError is an OSError", "    except ValueError:", ["test_tools"]),
    ("usage: the asking device's id served too", "bin/ollama1-gateway",
     '            if method == "GET" and route == "/v1/usage":\n                return self.send_json(200, gw.usage())',
     '            if method == "GET" and route == "/v1/usage":\n                return self.send_json(200, dict(gw.usage(), who=dev_id))',
     ["test_gateway"]),
    ("usage: whatever the reader returns is served", "bin/ollama1-gateway",
     '            return {"gpu": {k: self.usage_val.get(k) for k in USAGE_KEYS},', '            return {"gpu": dict(self.usage_val),',
     ["test_gateway"]),
    ("usage: memory in use taken from MemFree", "lib/o1stats.py",
     '            out["used_bytes"] = total - avail', '            out["used_bytes"] = total - info.get("MemFree", 0)', ["test_gpu", "test_gateway"]),
    ("usage: memory in use above the total served", "lib/o1stats.py",
     "if isinstance(avail, int) and 0 <= avail <= total:", "if isinstance(avail, int):", ["test_gpu"]),
    ("usage: memory not served", "bin/ollama1-gateway",
     '                    "ram": dict(self.ram_val)}', '                    }', ["test_gateway"]),
    ('idle: off still sleeps', 'lib/o1idle.py',
     'if i.get("enabled") is not True:',
     'if False:',
     ['test_idle']),
    ('idle: unsupported still sleeps', 'lib/o1idle.py',
     'if i.get("supported") is not True:',
     'if False:',
     ['test_idle']),
    ('idle: a request in flight ignored', 'lib/o1idle.py',
     'if i["inflight"] > 0:',
     'if False:',
     ['test_idle']),
    ('idle: a running download ignored', 'lib/o1idle.py',
     'if i["busy"]:',
     'if False:',
     ['test_idle']),
    ('idle: a running test or update ignored', 'lib/o1idle.py',
     'if i["tools"]:',
     'if False:',
     ['test_idle']),
    ('idle: a blocking inhibitor ignored', 'lib/o1idle.py',
     'if i["inhibitors"]:',
     'if False:',
     ['test_idle']),
    ('idle: a busy graphics card ignored', 'lib/o1idle.py',
     'if g is not None and g >= GPU_IDLE_PCT:',
     'if False:',
     ['test_idle']),
    ('idle: the graphics threshold off by one', 'lib/o1idle.py',
     'g >= GPU_IDLE_PCT',
     'g > GPU_IDLE_PCT',
     ['test_idle']),
    ('idle: boot time ignored', 'lib/o1idle.py',
     'since = max(last, float(i["boot_time"]), float(i.get("last_resume") or 0))',
     'since = max(last, float(i.get("last_resume") or 0))',
     ['test_idle']),
    ('idle: a resume ignored', 'lib/o1idle.py',
     'since = max(last, float(i["boot_time"]), float(i.get("last_resume") or 0))',
     'since = max(last, float(i["boot_time"]))',
     ['test_idle']),
    ('idle: minutes not clamped', 'lib/o1idle.py',
     'minutes = clamp_minutes(minutes)\n        now',
     'minutes = minutes\n        now',
     ['test_idle']),
    ('idle: a bool taken as minutes', 'lib/o1idle.py',
     'if not _int(minutes):',
     'if False:',
     ['test_idle']),
    ("idle: sleeps at the threshold's edge", 'lib/o1idle.py',
     'if idle < minutes * 60:',
     'if idle <= minutes * 60:',
     ['test_idle']),
    ('idle: a resume not noticed', 'lib/o1idle.py',
     '> RESUME_JUMP_S:',
     '> 10 ** 9:',
     ['test_idle']),
    ('idle: a probe that fails reads as nothing running', 'lib/o1idle.py',
     '        except Exception:\n            return None\n\n    def tick',
     '        except Exception:\n            return []\n\n    def tick',
     ['test_idle']),
    ('idle: any mem_sleep is deep', 'lib/o1idle.py',
     'return "deep" in words',
     'return True',
     ['test_idle']),
    ('config: a bool taken as a number', 'lib/o1idle.py',
     'return isinstance(v, int) and not isinstance(v, bool)',
     'return isinstance(v, int)',
     ['test_idle']),
    ('config: enabled by anything truthy', 'lib/o1idle.py',
     '"enabled": obj.get("enabled") is True,',
     '"enabled": bool(obj.get("enabled")),',
     ['test_idle']),
    ('config: minutes not clamped on a change', 'lib/o1idle.py',
     'out["minutes"] = clamp_minutes(obj["minutes"])',
     'out["minutes"] = obj["minutes"]',
     ['test_idle']),
    ('config: other keys accepted', 'lib/o1idle.py',
     'if set(obj) - {"enabled", "minutes"}:',
     'if False:',
     ['test_idle']),
    ("activity: a stale file's requests trusted", 'lib/o1idle.py',
     '"inflight": inflight if fresh else None',
     '"inflight": inflight',
     ['test_idle']),
    ('activity: a request ending below zero', 'lib/o1idle.py',
     'self.inflight = max(0, self.inflight - 1)',
     'self.inflight -= 1',
     ['test_idle']),
    ('probes: a delay lock blocks sleep', 'lib/o1idle.py',
     'if len(t) < 6 or t[-1] != "block":',
     'if len(t) < 6:',
     ['test_idle']),
    ("probes: a lock that isn't about sleep blocks it", 'lib/o1idle.py',
     'if any(re.fullmatch(',
     'if True or any(re.fullmatch(',
     ['test_idle']),
    ('probes: a later argument names a tool', 'lib/o1idle.py',
     'if b in TOOL_SCRIPTS or (i < 2 and b in TOOL_PROGRAMS):',
     'if i < 2 and (b in TOOL_SCRIPTS or b in TOOL_PROGRAMS):',
     ['test_idle']),
    ('wake: virtual cards included', 'lib/o1idle.py',
     'if VIRTUAL_NICS.match(n) or not os.path.exists(os.path.join(d, "device")):',
     'if not os.path.exists(os.path.join(d, "device")):',
     ['test_idle']),
    ('wake: bridges and veths included', 'lib/o1idle.py',
     'if VIRTUAL_NICS.match(n) or not os.path.exists(os.path.join(d, "device")):',
     'if VIRTUAL_NICS.match(n):',
     ['test_idle']),
    ("wake: a card that can't wake is set up", 'lib/o1idle.py',
     'sup = "g" in s.split(":", 1)[1]',
     'sup = True',
     ['test_idle']),
    ('wake: the link file says something else', 'lib/o1idle.py',
     'WakeOnLan=magic',
     'WakeOnLan=phy',
     ['test_idle']),
    ('wake: the link file rewritten every run', 'lib/o1idle.py',
     'if have != want:',
     'if True:',
     ['test_idle']),
    ('wake: more cards than the cap', 'lib/o1idle.py',
     'return out[:MAX_WAKE]',
     'return out',
     ['test_idle']),
    ('wake: junk published as a card', 'lib/o1idle.py',
     'if isinstance(m, str) and MAC_RX.match(m)',
     'if True',
     ['test_idle']),
    ('gateway: a poll counts as activity', 'bin/ollama1-gateway',
     'return self.send_json(200, gw.sleep_view())',
     'gw.activity.begin()\n                return self.send_json(200, gw.sleep_view())',
     ['test_gateway']),
    ('gateway: a finished request still counts as running', 'bin/ollama1-gateway',
     '                finally:\n                    gw.activity.end()',
     '                finally:\n                    pass',
     ['test_gateway']),
    ('gateway: a bad sleep setting accepted', 'bin/ollama1-gateway',
     'raise GatewayError(400, "bad_request", err)',
     'changes = {}',
     ['test_gateway']),
    ('probes: a program named anywhere counts', 'lib/o1idle.py',
     'if b in TOOL_SCRIPTS or (i < 2 and b in TOOL_PROGRAMS):',
     'if b in TOOL_SCRIPTS or b in TOOL_PROGRAMS:',
     ['test_idle']),
    ('wake: the link file leaves out the names and MAC policy', 'lib/o1idle.py',
     '"NamePolicy=keep kernel database onboard slot path\\nMACAddressPolicy=persistent\\nWakeOnLan=magic\\n"',
     '"WakeOnLan=magic\\n"',
     ['test_idle']),
    ('wake: an old-shaped file left as it was', 'lib/o1idle.py',
     'for path in existing_links(link_dir, mac) or [',
     'for path in [',
     ['test_idle']),
    ('wake: an address matched in one case only', 'lib/o1idle.py',
     'rx = re.compile(r"(?im)^',
     'rx = re.compile(r"(?m)^',
     ['test_idle']),
    ('activity: a restarted gateway starts as idle for ever', 'lib/o1idle.py',
     'self.last = clock()          # a gateway',
     'self.last = 0.0          # a gateway',
     ['test_idle']),
    ('activity: a garbage count read as none running', 'lib/o1idle.py',
     'inflight = inflight if _int(inflight) and 0 <= inflight < 100000 else None',
     'inflight = inflight if _int(inflight) and 0 <= inflight < 100000 else 0',
     ['test_idle']),
    ('idle: an unknown request state allowed', 'lib/o1idle.py',
     'if i.get("inflight") is None:',
     'if False:',
     ['test_idle']),
    ('idle: a card with no reading ignored', 'lib/o1idle.py',
     'if g is None and i.get("gpu_present") is not False:',
     'if False:',
     ['test_idle']),
    ('idle: a card guessed absent', 'lib/o1idle.py',
     'if g is None and i.get("gpu_present") is not False:',
     'if g is None and i.get("gpu_present") is True:',
     ['test_idle']),
    ('idle: the load average ignored', 'lib/o1idle.py',
     'if la > LOAD_BUSY:',
     'if False:',
     ['test_idle']),
    ('idle: an unknown load average allowed', 'lib/o1idle.py',
     'if la is None:',
     'if False:',
     ['test_idle']),
    ('idle: an unknown boot time allowed', 'lib/o1idle.py',
     'if i.get("boot_time") is None:',
     'if False:',
     ['test_idle']),
    ('idle: a failed boot time read as the epoch', 'lib/o1idle.py',
     '    return None\n\n\ndef loadavg1',
     '    return 0.0\n\n\ndef loadavg1',
     ['test_idle']),
    ('idle: a short wake not counted', 'lib/o1idle.py',
     '            self.last_resume = self.clock()\n            self.last_reason = None',
     '            self.last_reason = None',
     ['test_idle']),
    ('safe: the settings file read through a link',
     [('lib/o1idle.py', 'from o1common import Paths, read_json_safe, write_json_atomic', 'from o1common import Paths, read_json, write_json_atomic'), ('lib/o1idle.py', 'read_json_safe(path or config_file(), {}, max_bytes=4096)', 'read_json(path or config_file(), {})')],
     ['test_idle']),
    ('safe: the activity file read through a link',
     [('lib/o1idle.py', 'from o1common import Paths, read_json_safe, write_json_atomic', 'from o1common import Paths, read_json, write_json_atomic'), ('lib/o1idle.py', 'read_json_safe(path or activity_file(), {}, max_bytes=4096)', 'read_json(path or activity_file(), {})')],
     ['test_idle']),
    ('lan: a /8 accepted', 'lib/setuplib.sh',
     'sys.exit(0 if n.prefixlen >= 16 and any(',
     'sys.exit(0 if any(',
     ['test_setuplib']),
    ('lan: a public network accepted', 'lib/setuplib.sh',
     'n.prefixlen >= 16 and any(n.subnet_of(p) for p in priv) else 1)',
     'n.prefixlen >= 16 else 1)',
     ['test_setuplib']),
    ('lan: the flag ignored', 'lib/setuplib.sh',
     '  [ "${LAN_PUBLIC_OK:-0}" = 1 ] && return 0\n',
     '',
     ['test_setuplib']),
    ('lan: everything accepted with the flag', 'lib/setuplib.sh',
     '  [ "${LAN_PUBLIC_OK:-0}" = 1 ] && return 0\n  lan_private "$1"',
     '  [ "${LAN_PUBLIC_OK:-0}" = 1 ] && return 0\n  return 0',
     ['test_setuplib']),
    ('ssh: a client inside the LAN called outside', 'lib/setuplib.sh',
     'sys.exit(1 if ipaddress.ip_address(sys.argv[1]) in ipaddress.ip_network(sys.argv[2]) else 0)',
     'sys.exit(0)',
     ['test_setuplib']),
    ('ssh: SSH_CLIENT not read', 'lib/setuplib.sh',
     'elif [ -n "${SSH_CLIENT:-}" ]; then ip=${SSH_CLIENT%% *}',
     'elif false; then ip=x',
     ['test_setuplib']),
    ('ssh: a garbage address believed', 'lib/setuplib.sh',
     '[[ "$ip" =~ ^[0-9]{1,3}(\\.[0-9]{1,3}){3}$ ]] && printf \'%s\' "$ip"',
     'printf \'%s\' "$ip"',
     ['test_setuplib']),
    ("usage: reading not cached", "bin/ollama1-gateway",
     "if self.usage_at is None or now - self.usage_at >= USAGE_CACHE_S:", "if True:", ["test_gateway"]),
    ("usage: a hardware serial served too", "lib/o1gpu.py",
     '    out = {"busy_pct": None, "vram_used_bytes": None, "vram_total_bytes": None}\n    try:\n        if vendor == "amd":',
     '    out = {"busy_pct": None, "vram_used_bytes": None, "vram_total_bytes": None, "serial": _read(_sys() + "/class/drm/card0/device/serial_number")}\n    try:\n        if vendor == "amd":',
     ["test_gpu"]),
    ("usage: a missing file raises", "lib/o1gpu.py",
     'out["busy_pct"] = _pct(_read(dev + "/gpu_busy_percent"))',
     'out["busy_pct"] = _pct(open(dev + "/gpu_busy_percent").read())', ["test_gpu", "test_gateway"]),
    ("usage: out-of-range busy percent served", "lib/o1gpu.py",
     "    return v if 0 <= v <= 100 else None", "    return v", ["test_gpu"]),
    ("step3: reserve ignored when growing /", "lib/setuplib.sh",
     'run lvextend -r -l "+$((free - keep))" /dev/ubuntu-vg/ubuntu-lv', 'run lvextend -r -l "+$free" /dev/ubuntu-vg/ubuntu-lv',
     ["test_setuplib"]),
    ("step3: result of lvextend not checked", "lib/setuplib.sh",
     '    [ "$free" = "$keep" ] || die', "    true || die", ["test_setuplib"]),
    ("step3: grows even at the reserve", "lib/setuplib.sh",
     '  if [ "$free" -gt "$keep" ]; then', '  if [ "$free" -ge "$keep" ]; then', ["test_setuplib"]),
    # the server's name is the owner's (6b347)
    ("name: any server name accepted", "lib/o1common.py",
     'return isinstance(name, str) and bool(NAME_RX.match(name)) and not name.endswith("-")', "return True",
     ["test_name"]),
    ("name: a name ending in a hyphen accepted", "lib/o1common.py",
     ' and not name.endswith("-")', "", ["test_name"]),
    ("name: no length limit", "lib/o1common.py", "{0,31}$", "{0,99}$", ["test_name"]),
    ("name: absent server_name is not ollama1", "lib/o1common.py",
     "return n if valid_server_name(n) else LEGACY_NAME", 'return n if valid_server_name(n) else ""',
     ["test_name", "test_cloudflare"]),
    ("name: hostnames already in config overwritten", "lib/o1common.py",
     'if not cfg.get("hostname_gateway") and zone:', "if zone:", ["test_name"]),
    ("name: the admin hostname is not derived from the name", "lib/o1common.py",
     'cfg["hostname_admin"] = "%s-admin.%s" % (n, zone)', 'cfg["hostname_admin"] = "admin.%s" % zone',
     ["test_name", "test_cloudflare"]),
    ("name: tunnel name in config ignored", "lib/o1common.py",
     '"tunnel": cfg.get("tunnel_name") or n,', '"tunnel": n,', ["test_name", "test_cloudflare"]),
    ("name: service token name in config ignored", "lib/o1common.py",
     '"token": cfg.get("token_name") or n + "-app",', '"token": n + "-app",', ["test_name", "test_cloudflare"]),
    ("name: owner left out of the admin policy name", "lib/o1common.py",
     '("%s admin - %s only" % (n, owner) if owner else n + " admin only")', '(n + " admin only")',
     ["test_name", "test_cloudflare"]),
    ("name: Cloudflare helper still names the tunnel ollama1", "bin/ollama1-cf-access",
     'TUNNEL, TOKEN_NAME, POL_ADMIN, POL_APP = names["tunnel"],', 'TUNNEL, TOKEN_NAME, POL_ADMIN, POL_APP = "ollama1",',
     ["test_cloudflare"]),
    ("name: Cloudflare helper runs without a zone", "bin/ollama1-cf-access",
     'if not cfg.get("hostname_gateway") or not cfg.get("hostname_admin"):', "if False:", ["test_cloudflare"]),
    ("name: the panel page still says ollama1", "bin/ollama1-admin",
     '.replace("{{NAME}}", html.escape(cfg.get("server_name") or ""))', '.replace("{{NAME}}", "ollama1")',
     ["test_admin"]),
    ("setup: invalid server name accepted", "lib/setuplib.sh",
     'valid_name() { [[ "$1" =~ ^[a-z][a-z0-9-]{0,31}$ ]] && [[ "$1" != *- ]]; }', "valid_name() { true; }",
     ["test_setuplib"]),
    ("setup: server name may end in a hyphen", "lib/setuplib.sh", ' && [[ "$1" != *- ]]; }', "; }", ["test_setuplib"]),
    ("setup: LAN range not checked", "lib/setuplib.sh",
     "  [[ \"$1\" =~ ^[0-9.]{7,15}/[0-9]{1,2}$ ]] || return 1\n", "", ["test_setuplib"]),
    ("setup: old install without a name is not ollama1", "lib/setuplib.sh",
     'if [ -z "$have" ] && [ -e "$CONFIG_JSON" ]; then have=$LEGACY_SERVER_NAME; fi', "true",
     ["test_setuplib"]),
    ("setup: an existing install gets renamed", "lib/setuplib.sh",
     'if [ -n "$have" ] && [ "$n" != "$have" ]; then', "if false; then", ["test_setuplib"]),
    ("setup: saved name ignored on a re-run", "lib/setuplib.sh", '[ -n "$n" ] || n=$(saved SERVER_NAME)', "true",
     ["test_setuplib"]),
    # ---- image and video generation (6b356)
    ("gen: prompt length not capped", "lib/o1gen.py", "    if len(prompt) > PROMPT_MAX:", "    if False:",
     ["test_generate"]),
    ("gen: unknown request keys accepted (a graph could ride along)", "lib/o1gen.py", "    if extra:", "    if False:",
     ["test_generate"]),
    ("gen: picture size not capped", "lib/o1gen.py", "        if w * h > IMAGE_MAX_PIXELS:", "        if False:",
     ["test_generate"]),
    ("gen: sizes not kept to a multiple", "lib/o1gen.py", "or v > hi or v % align:", "or v > hi:",
     ["test_generate"]),
    ("gen: frames not kept to 4n+1", "lib/o1gen.py", "or (frames - 1) % 4:", ":",
     ["test_generate"]),
    ("gen: a second job starts while one runs", [
        ("lib/o1gen.py", "        if not self.hooks.slot_acquire():", "        if False:"),
        ("lib/o1gen.py", '''        with self.lock:
            if self.active is not None:
                raise GenError(409, "busy", "the server is already making one")
        if False:''', '''        with self.lock:
            pass
        if False:'''),
        ("lib/o1gen.py", '''            with self.lock:
                if self.active is not None:
                    raise GenError(409, "busy", "the server is already making one")
                job =''', '''            with self.lock:
                job =''')], ["test_generate"]),
    ("gen: a job starts while a chat holds the card", "lib/o1gen.py", "        if not self.hooks.slot_acquire():",
     "        if False:", ["test_generate"]),
    ("gen: a chat is answered during a job", "bin/ollama1-gateway", "            if gw.gen.running():", "            if False:",
     ["test_generate"]),
    ("gen: Ollama's models stay loaded for a job", "bin/ollama1-gateway",
     '            for name in names:\n                gw.unload(name, "unload: generation")', "            pass",
     ["test_generate"]),
    ("gen: unload not confirmed", "bin/ollama1-gateway", "        if left:\n            raise o1gen.GenError(503",
     "        if False:\n            raise o1gen.GenError(503", ["test_generate"]),
    ("gen: the card is not freed after a job", "lib/o1gen.py", '"POST", "/free", {', '"POST", "/nothing", {',
     ["test_generate"]),
    ("gen: no wait for the card to look free", "lib/o1gen.py",
     "            if used <= max(int(2.5 * (1 << 30)), total * 0.15):", "            if True:", ["test_generate"]),
    ("gen: the GPU slot is not given back", "lib/o1gen.py",
     "                    if self.active is j:\n                        self.active = None\n                self.hooks.slot_release()",
     "                    if self.active is j:\n                        self.active = None", ["test_generate"]),
    ("gen: a result that isn't a picture is relayed", "lib/o1gen.py",
     "ctype = sniff(j.kind, data, j.fmt) if data else None", 'ctype = "image/png" if data else None',
     ["test_generate"]),
    ("gen: results never expire", "lib/o1gen.py",
     "if j.finished is not None and now - j.finished >= RESULT_KEEP_S:", "if False:", ["test_generate"]),
    ("gen: another device can read a job", "lib/o1gen.py", "j.dev_id != dev_id or ", "", ["test_generate"]),
    ("gen: a running job is not activity", "lib/o1gen.py", "            self.activity.begin()", "            pass",
     ["test_generate"]),
    ("gen: polls are not activity", "lib/o1gen.py", "            self.activity.touch()", "            pass",
     ["test_generate"]),
    ("gen: activity ends with the job, not 120 s after the last poll", "lib/o1gen.py",
     "ACTIVITY_TAIL_S = 120 ", "ACTIVITY_TAIL_S = 0 ", ["test_generate"]),
    ("gen: a job nobody polls runs on", "lib/o1gen.py",
     "                j.cancel.set()          # nobody is asking any more: stop wasting the card", "                pass",
     ["test_generate"]),
    ("gen: Stop does not interrupt ComfyUI", "lib/o1gen.py", '("/interrupt", {"prompt_id": pid})',
     '("/nothing", {"prompt_id": pid})', ["test_generate"]),
    ("gen: ComfyUI reached at any address", "lib/o1gen.py",
     '        self.local = self.host in ("127.0.0.1", "localhost", "::1")', "        self.local = True",
     ["test_generate"]),
    ("gen: the newer combo spelling not read", "lib/o1gen.py", '            if first == "COMBO" and', "            if False and",
     ["test_generate"]),
    ("gen: no animated WebP fallback", "lib/o1gen.py", '            elif base and has("SaveAnimatedWEBP"):',
     "            elif False:", ["test_generate"]),
    ("gen: a model file that is missing still says yes", "lib/o1gen.py",
     "                return name in (self._options(info, node, field) or [])", "                return True",
     ["test_generate"]),
    ("gen: result size not capped", "lib/o1gen.py", 'RESULT_MAX = {"image": 16 << 20,', 'RESULT_MAX = {"image": 1 << 40,',
     ["test_generate"]),
    ("gen: the request's numbers ride in the prompt text", "lib/o1gen.py",
     '"CLIPTextEncode", "inputs": {"text": p["prompt"], "clip": ["1", 1]}}',
     '"CLIPTextEncode", "inputs": {"text": p["prompt"] + str(p), "clip": ["1", 1]}}', ["test_generate"]),
    ("gen: a failed job explains itself", "lib/o1gen.py", 'out["error"] = JOB_ERROR',
     'out["error"] = JOB_ERROR + " " + str(j.params)', ["test_generate"]),
    ("gen: ComfyUI's port open to the ollama user too", "config/ollama1.nft.in",
     "tcp dport 8188 fib daddr type local meta skuid != { 0, @UID_O1GW@ } counter reject with tcp reset",
     "tcp dport 8188 fib daddr type local meta skuid != { 0, @UID_O1GW@, @UID_OLLAMA@ } counter reject with tcp reset",
     ["test_generate"]),
    ("gen: ComfyUI's port guard skips the machine's own addresses", "config/ollama1.nft.in",
     "tcp dport 8188 fib daddr type local meta", "tcp dport 8188 meta", ["test_generate"]),
    ("gen: ComfyUI's port not guarded", "config/ollama1.nft.in",
     "        tcp dport 8188 fib daddr type local meta skuid != { 0, @UID_O1GW@ } counter reject with tcp reset\n", "",
     ["test_generate"]),
    ("gen: ComfyUI listens on every address", "tools/install-comfyui.sh", "--listen 127.0.0.1 --port", "--listen 0.0.0.0 --port",
     ["test_generate"]),
    ("gen: ComfyUI runs as root", "tools/install-comfyui.sh", "User=$USER_NAME\nSupplementaryGroups", "User=root\nSupplementaryGroups",
     ["test_generate"]),
    ("gen: the installer accepts root", "tools/install-comfyui.sh", '[ "$USER_NAME" != root ] || die', "true || die",
     ["test_generate"]),
    ("gen: the installer accepts any login text", "tools/install-comfyui.sh",
     'if [ -n "$USER_NAME" ] && ! [[ "$USER_NAME" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]; then', "if false; then", ["test_generate"]),
    ("gen: pictures keep their prompt in metadata", "tools/install-comfyui.sh", "--disable-metadata ", "", ["test_generate"]),
    ("gen: results written to a disk", "tools/install-comfyui.sh", "--output-directory /run/comfyui/out", "--output-directory $DIR/output",
     ["test_generate"]),
    ("gen: a short model download accepted", "tools/install-comfyui.sh", '[ "$size" -ge "$4" ] || die "$2 came to only', 'true || die "$2 came to only',
     ["test_generate"]),
    ("gen: ComfyUI results never swept", "tools/install-comfyui.sh", "-mmin +15 -delete", "-mmin +15", ["test_generate"]),

    ("cpu: hwmon picked by its number, not its name", "lib/o1cpu.py",
     "if n in HWMON_NAMES and n not in found:", 'if d == "hwmon0" and n not in found:', ["test_cpu"]),
    ("cpu: sensor values not bounded (garbage and NaN shown)", "lib/o1cpu.py",
     "if math.isnan(v) or math.isinf(v) or v < lo or v > hi:", "if False:", ["test_cpu"]),
    ("cpu: model text from the machine not cleaned", "lib/o1cpu.py",
     "ch.isprintable() and ch not in _BAD_TEXT", "True", ["test_cpu"]),
    ("cpu: utilisation divides by zero", "lib/o1cpu.py",
     "if dt <= 0 or db < 0:", "if False:", ["test_cpu"]),
    ("cpu: a symlinked sysfs file is followed", "lib/o1cpu.py",
     "os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK", "os.O_RDONLY | os.O_NONBLOCK", ["test_cpu"]),
    ("cpu: core list not capped", "lib/o1cpu.py",
     "for n, nm in found[:MAX_CORES]]", "for n, nm in found]", ["test_cpu"]),
    ("cpu: /proc/stat core list not capped", "lib/o1cpu.py",
     "if not parts[0].startswith(\"cpu\") or len(out) > MAX_CORES:", "if not parts[0].startswith(\"cpu\"):", ["test_cpu"]),
    ("cpu: peak temperature not kept", "lib/o1cpu.py",
     "if self.peak_c is None or c > self.peak_c:", "if True:", ["test_cpu"]),
    ("cpu: panel writes the model as markup", "bin/ollama1-admin",
     "$('cpumodel').textContent=c.model||'';", "$('cpumodel').innerHTML=c.model||'';", ["test_cpu"]),
    ("cpu: older 7-column history thrown away", "bin/ollama1-admin",
     "len(row) in (7, HISTORY_COLS)", "len(row) == HISTORY_COLS", ["test_cpu"]),
    ("setup: an empty serial matches a disk", "lib/setuplib.sh",
     '  [ -n "$1" ] || return 0   # no serial given: no disk (an empty one would match any)\n', "",
     ["test_setuplib"]),
    ("gpu-tune: memory clock not clamped to the card's range", "lib/o1gputune.py",
     "t = min(stock_max + MCLK_BUMP, range_max)", "t = stock_max + MCLK_BUMP", ["test_gputune"]),
    ("gpu-tune: card picked by its number", "lib/o1gputune.py",
     'for dev in sorted(glob.glob(root + "/bus/pci/devices/*")):', 'for dev in [root + "/class/drm/card0/device"]:',
     ["test_gputune"]),
    ("gpu-tune: feature mask 0xffffffff", "lib/o1gputune.py",
     "return (v | OD_BIT) & 0xFFFFFFFF", "return 0xFFFFFFFF", ["test_gputune"]),
    ("gpu-tune: power limit not the card's maximum", "lib/o1gputune.py", "        return None\n    return mx\n",
     "        return None\n    return dflt\n", ["test_gputune"]),
    ("gpu-tune: power limit above the card's maximum", "lib/o1gputune.py", "        return None\n    return mx\n",
     "        return None\n    return mx + 10 ** 6\n", ["test_gputune"]),
    ("gpu-tune: no revert after a failed check", "lib/o1gputune.py",
     '        if why:\n            chk["result"] = "reverted"', '        if False:\n            chk["result"] = "reverted"',
     ["test_gputune"]),
    ("gpu-tune: check runs on after a kernel error", "lib/o1gputune.py",
     '                if errs:\n                    return tokens, secs, answers, "the kernel logged: "',
     '                if False:\n                    return tokens, secs, answers, "the kernel logged: "',
     ["test_gputune"]),
    ("gpu-tune: the boot it last ran in not read", "lib/o1gputune.py",
     'if self.st.get("boot_checked") != a["boot"]:', "if False:", ["test_gputune"]),
    ("gpu-tune: an error in the boot it last ran in kept", "lib/o1gputune.py",
     '                    if errs:\n                        self.revert(card, "the boot it last ran in logged: "',
     '                    if False:\n                        self.revert(card, "the boot it last ran in logged: "',
     ["test_gputune"]),
    ("gpu-tune: a check the machine never finished is forgotten", "lib/o1gputune.py",
     'if chk.get("result") == "running" and chk.get("boot") != now and not self.st.get("reverted"):', "if False:",
     ["test_gputune"]),
    ("gpu-tune: re-applied at boot after a revert", "lib/o1gputune.py",
     "        if self.active():\n            res = self.apply_card(card)",
     '        if self.st.get("wanted") == "on":\n            res = self.apply_card(card)', ["test_gputune"]),
    ("gpu-tune: re-applied by apply after a revert", "lib/o1gputune.py",
     '        if self.st.get("reverted"):\n            self.say("kept at stock after: %s. To try again',
     '        if False:\n            self.say("kept at stock after: %s. To try again', ["test_gputune"]),
    ("gpu-tune: junction temperature not watched", "lib/o1gputune.py",
     "JUNCTION_MAX_C = 105", "JUNCTION_MAX_C = 200", ["test_gputune"]),
    ("gpu-tune: memory temperature not watched", "lib/o1gputune.py",
     "MEM_MAX_C = 100", "MEM_MAX_C = 200", ["test_gputune"]),
    ("gpu-tune: slower than stock kept", "lib/o1gputune.py",
     'and tps < SLOWER_LIMIT * m["stock_tps"]:', "and False:", ["test_gputune"]),
    ("gpu-tune: level left in manual", "lib/o1gputune.py",
     '                    self.io.write(card.dev + "/" + LEVEL_FILE, "auto")', "                    pass",
     ["test_gputune"]),
    ("gpu-tune: not set again after a wake", "config/ollama1-sleep-hook",
     "      systemctl start --no-block ollama1-gpu-tune.service", "      true", ["test_gputune"]),
    ("gpu-tune: on by default again", "lib/setuplib.sh", "  echo default\n}", "  echo on\n}", ["test_gputune"]),
    ("gpu-tune: a saved on is not kept by a re-run", "lib/setuplib.sh", 'for v in "$1" "$2" "$3"; do',
     'for v in "$1" "$2"; do', ["test_gputune"]),
    ("gpu-tune: setup's opt-out ignored", "lib/setuplib.sh",
     "off|0|no|false) echo off; return 0 ;;", "off|0|no|false) echo on; return 0 ;;", ["test_gputune"]),
]


def main():
    only = sys.argv[1] if len(sys.argv) > 1 else ""
    survived = []
    ran = 0
    for m in MUTANTS:
        if len(m) == 3:
            name, rel, tests = m
            old = new = None
        else:
            name, rel, old, new, tests = m
        if only and only not in name:
            continue
        ran += 1
        work = tempfile.mkdtemp(prefix="o1mut-")
        try:
            for d in ("lib", "bin", "config", "systemd", "tools"):
                shutil.copytree(os.path.join(KIT, d), os.path.join(work, d))
            edits = rel if isinstance(rel, list) else [(rel, old, new)]
            broken = False
            for erel, eold, enew in edits:
                path = os.path.join(work, erel)
                src = open(path).read()
                if src.count(eold) != 1:
                    print("BROKEN  %-50s  (the original text appears %d times)" % (name, src.count(eold)))
                    broken = True
                    break
                open(path, "w").write(src.replace(eold, enew))
            if broken:
                survived.append(name)
                continue
            env = dict(os.environ, OLLAMA1_TEST_LIB=os.path.join(work, "lib"),
                       OLLAMA1_TEST_BIN=os.path.join(work, "bin"), OLLAMA1_TEST_TOOLS=os.path.join(work, "tools"),
                       OLLAMA1_TEST_CONFIG=os.path.join(work, "config"),
                       PYTHONWARNINGS="ignore")
            env.pop("OLLAMA1_PREFIX", None)
            try:
                r = subprocess.run([sys.executable, "-m", "unittest"] + tests, cwd=HERE, env=env,
                                   capture_output=True, text=True, timeout=300)
            except subprocess.TimeoutExpired:
                # e.g. root blocking on a planted FIFO: the tests hang instead of passing
                print("killed  %s  (the tests hung)" % name)
                continue
            if r.returncode == 0:
                print("SURVIVED %-50s  (%s still pass)" % (name, " ".join(tests)))
                survived.append(name)
            else:
                print("killed  %s" % name)
        finally:
            shutil.rmtree(work, ignore_errors=True)
    print("\n%d mutants, %d killed, %d survived" % (ran, ran - len(survived), len(survived)))
    return 1 if survived else 0


if __name__ == "__main__":
    sys.exit(main())
