#!/usr/bin/env python3
"""Mutation checks: break each key protection on purpose, in a copy of the
kit, and make sure the tests notice. A mutant the tests don't kill means a
protection has no test watching it.

    python3 tests/mutate.py            # all mutants
    python3 tests/mutate.py skew       # the ones whose name contains "skew"
"""
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.dirname(HERE)

# (name, file, original text, mutated text, test modules that must fail)
MUTANTS = [
    ("sig: timestamp skew not checked", "lib/o1auth.py",
     "if abs(now - ts) > self.skew:", "if False:", ["test_gateway"]),
    ("sig: nonce replay not checked", "lib/o1auth.py",
     'if not self.nonces.check_and_add(dev_id + ":" + pre["nonce"], self.clock()):', "if False:", ["test_gateway"]),
    ("sig: signature not verified", "lib/o1auth.py",
     'if not ed25519_verify(dev["public_key"], msg, pre["sig"]):', "if False:", ["test_gateway", "test_vectors"]),
    ("sig: unpaired device accepted", "lib/o1auth.py",
     "dev = self.devices().get(dev_id)",
     "dev = self.devices().get(dev_id) or next(iter(self.devices().values()), None)", ["test_gateway"]),
    ("sig: body not covered", "lib/o1auth.py",
     '"ollama1-req-v1", method.upper(), path, body_sha_hex,', '"ollama1-req-v1", method.upper(), path, "",',
     ["test_gateway", "test_vectors"]),
    ("sig: pre-restart signatures accepted", "lib/o1auth.py",
     "if ts < self.start_time:", "if False:", ["test_gateway"]),
    ("jwt: signature not verified", "lib/o1jwt.py",
     "if not rsa_pkcs1_sha256_verify(", "if False and not rsa_pkcs1_sha256_verify(", ["test_gateway", "test_jwt"]),
    ("jwt: audience not checked", "lib/o1jwt.py",
     "if not any(isinstance(a, str) and hmac.compare_digest(a, self.aud) for a in auds):", "if False:",
     ["test_gateway", "test_jwt"]),
    ("jwt: issuer not checked", "lib/o1jwt.py", "if payload.get(\"iss\") != self.issuer:", "if False:",
     ["test_gateway"]),
    ("jwt: expiry not checked", "lib/o1jwt.py", "now > exp + LEEWAY", "now > exp + 10**9",
     ["test_gateway", "test_jwt"]),
    ("jwt: not-before not checked", "lib/o1jwt.py", "now + LEEWAY < nbf", "False", ["test_gateway"]),
    ("jwt: http certs URL allowed", "lib/o1jwt.py", 'if not url.startswith("https://") and not allow_insecure:',
     "if False:", ["test_jwt"]),
    ("gateway: service token not pinned", "bin/ollama1-gateway",
     'if want and claims.get("common_name") != want:', "if False:", ["test_gateway"]),
    ("gateway: host not checked", "bin/ollama1-gateway",
     'if host != self.cfg["hostname_gateway"].lower():', "if False:", ["test_gateway"]),
    ("gateway: LAN listener open when LAN mode is off", "bin/ollama1-gateway",
     'if not self.cfg.get("lan_mode"):', "if False:", ["test_gateway"]),
    ("gateway: LAN listener open to any address", "bin/ollama1-gateway",
     "if ipaddress.ip_address(client_ip) not in self.lan_net:", "if False:", ["test_gateway"]),
    ("gpu: fit estimate ignored", "bin/ollama1-gateway", "            if need <= budget:\n                return c",
     "            if True:\n                return c", ["test_gateway"]),
    ("gpu: CPU spill not refused", "bin/ollama1-gateway", "if share < 1.0:", "if False:", ["test_gateway"]),
    ("gpu: load options passed through", "bin/ollama1-gateway",
     "clean = {k: v for k, v in opts.items() if k in SAMPLING_OPTIONS}", "clean = dict(opts)", ["test_gateway"]),
    ("gpu: cloud models allowed", "lib/o1ollama.py",
     'if entry.get("remote_model") or entry.get("remote_host"):', "if False:", ["test_gateway"]),
    ("pair: wrong-code limit gone", "lib/o1pair.py", "        if left <= 0:", "        if False:", ["test_gateway"]),
    ("pair: rate limit gone", "bin/ollama1-gateway",
     'if now - gw.pair["last_try"] < PAIR_MIN_INTERVAL:', "if False:", ["test_gateway"]),
    ("pair: window reusable after a success", "lib/o1pair.py",
     '    close_window(w["id"])  # one success closes the window', "    pass", ["test_gateway"]),
    ("pair: root step skips the code", "lib/o1pair.py",
     'if not check_pair_mac(w["code"], name, pub_b64, ts, nonce, mac):', "if False:", ["test_gateway"]),
    ("pair: nonce reuse accepted", "lib/o1pair.py", 'if nonce in w.get("nonces", []):', "if False:",
     ["test_gateway"]),
    ("pair: window never expires", [
        ("lib/o1pair.py", 'if float(w["expires_at"]) <= now or not w["id"] or not w["code"]:', "if False:"),
        ("lib/o1pair.py", 'and w["expires_at"] > now:', ":")], ["test_gateway"]),
    ("pair: allowed on the LAN listener", "bin/ollama1-gateway",
     '            if lan:\n                raise GatewayError(403, "pair_closed"',
     '            if False:\n                raise GatewayError(403, "pair_closed"', ["test_gateway"]),
    ("F1: gateway errors keep the connection open", "bin/ollama1-gateway",
     '                self.send_header("Connection", "close")\n                self.close_connection = True\n',
     "                pass\n", ["test_gateway"]),
    ("F1: panel errors keep the connection open", "bin/ollama1-admin",
     '                self.send_header("Connection", "close")\n                self.close_connection = True\n',
     "                pass\n", ["test_admin"]),
    ("F3: body read before the signature headers", "bin/ollama1-gateway",
     "                    pre = gw.verifier.precheck(method, self.path, self.headers)\n"
     "                    body = self.read_body(max_body)\n",
     "                    body = self.read_body(max_body)\n"
     "                    pre = gw.verifier.precheck(method, self.path, self.headers)\n", ["test_gateway"]),
    ("F3: no cap on requests in flight", "bin/ollama1-gateway",
     "if not gw.inflight.acquire(blocking=False):", "if False:", ["test_gateway"]),
    ("F5: exception mid-stream breaks the stream", "bin/ollama1-gateway",
     "            except Exception as e:\n                # e.g. Ollama restarting",
     "            except ZeroDivisionError as e:\n                # e.g. Ollama restarting", ["test_gateway"]),
    ("KV: models kept across devices", "bin/ollama1-gateway",
     "if self.last_device is None or self.last_device == dev_id:", "if True:", ["test_gateway"]),
    ("dash: pairing code drawn blank", "lib/o1big.py", "for c in g[i])", "for c in g)", ["test_big"]),
    ("ram: flagged models held to VRAM", "bin/ollama1-gateway",
     "        if not ram:\n            return self.ensure_on_gpu(name)", "        if True:\n            return self.ensure_on_gpu(name)",
     ["test_gateway"]),
    ("ram: every model may use RAM", "bin/ollama1-gateway", "            ram = gw.is_ram_model(name)",
     "            ram = True", ["test_gateway"]),
    ("ram: swap not checked", "bin/ollama1-gateway",
     "if swapped > (512 << 20) or int(after.get(\"MemAvailable\", 1 << 40)) < (1 << 30):", "if False:",
     ["test_gateway"]),
    ("ram: loads next to other models", "bin/ollama1-gateway", "        if not victims:\n            return",
     "        if True:\n            return", ["test_gateway"]),
    ("ram: no context step-down", "bin/ollama1-gateway", "            tries += [c for c in (4096, 2048) if c < n_ctx]",
     "            pass", ["test_gateway"]),
    ("allow: unknown flags accepted", "lib/o1common.py", "        elif any(fl not in ALLOW_FLAGS for fl in flags):",
     "        elif False:", ["test_gateway"]),
    ("access: 'none' mode on by default", "bin/ollama1-gateway", '        if self.cfg.get("access") == "none":',
     '        if self.cfg.get("access") != "cloudflare_only":', ["test_gateway"]),
    ("none: any Host accepted", "bin/ollama1-gateway",
     'if not re.match(r"^(127\\.0\\.0\\.1|localhost)(:[0-9]{1,5})?$", host):', "if False:", ["test_gateway"]),
    ("none: Origin accepted", "bin/ollama1-gateway", '            if headers.get("Origin") is not None:',
     "            if False:", ["test_gateway"]),
    ("none: non-JSON POST accepted", "bin/ollama1-gateway", '            if method == "POST" and (headers.get',
     '            if False and (headers.get', ["test_gateway"]),
    ("none: starts next to a tunnel", "bin/ollama1-gateway",
     '    if cfg.get("access") == "none" and cfg.get("tunnel_id"):', "    if False:", ["test_gateway"]),
    ("ram: spilled model kept next to a GPU-only job", "bin/ollama1-gateway",
     'return self.is_ram_model(n) or int(m.get("size_vram") or 0) < int(m.get("size") or 0)',
     "return self.is_ram_model(n)", ["test_gateway"]),
    ("mem: mmap left on for ram models", "bin/ollama1-gateway", '            clean["use_mmap"] = False',
     "            pass", ["test_gateway"]),
    ("mem: warm load with mmap", "bin/ollama1-gateway", '            opts["use_mmap"] = False   # see shape()',
     "            pass", ["test_gateway"]),
    ("mem: margin 6 GiB again", "bin/ollama1-gateway",
     'margin = max(8 << 30, int(mi.get("MemTotal", 0) * 0.12), int(self.cfg.get("ram_margin_gib") or 8) << 30)',
     "margin = 6 << 30", ["test_gateway"]),
    ("mem: Ollama's cap ignored", "bin/ollama1-gateway", "        if high:\n", "        if False:\n",
     ["test_gateway"]),
    ("mem: compute buffers not counted", "lib/o1ollama.py",
     "(RAM_COMPUTE_BYTES if ram else (256 << 20))", "(256 << 20)", ["test_gateway"]),
    ("mem: OOM not reported", "bin/ollama1-gateway",
     "        if before is not None and after is not None and after > before:", "        if False:",
     ["test_gateway"]),
    ("mem: Ollama dying taken for the client leaving", "bin/ollama1-gateway",
     '        except OSError:\n            raise GatewayError(502, "ollama", "Ollama stopped while loading the model")',
     '        except ZeroDivisionError:\n            raise GatewayError(502, "ollama", "Ollama stopped while loading the model")',
     ["test_gateway"]),
    ("repack: VRAM counted while repacking is on", "bin/ollama1-gateway",
     '        host_only = ram and not self.cfg.get("ollama_no_repack")', "        host_only = False", ["test_gateway"]),
    ("repack: mmap forced off with repacking off", "bin/ollama1-gateway",
     '        if ram and not self.cfg.get("ollama_no_repack"):\n            # With repacking on',
     '        if ram:\n            # With repacking on', ["test_gateway"]),
    ("info: every detected field served", "bin/ollama1-gateway",
     '                return self.send_json(200, {"gpu": {"vendor": g.get("vendor"), "name": g.get("name"),\n'
     '                                                    "vram_bytes": g.get("vram_bytes")}})',
     '                return self.send_json(200, {"gpu": dict(g)})', ["test_gateway"]),
    ("info: a missing card is never looked for again", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if False:', ["test_gateway"]),
    ("info: a missing card is looked for on every request", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if not (self.gpu_info or {}).get("vendor"):', ["test_gateway"]),
    ("info: a found card is looked for again", "bin/ollama1-gateway",
     '        if not (self.gpu_info or {}).get("vendor") and time.monotonic() - self.gpu_at >= GPU_RECHECK_S:',
     '        if time.monotonic() - self.gpu_at >= GPU_RECHECK_S:', ["test_gateway"]),
    ("money: panel shows more than cents", "bin/ollama1-admin",
     "(c/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})",
     "Math.abs(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4})", ["test_admin"]),
    ("money: panel sub-cent shown as $0.00", "bin/ollama1-admin",
     "if(v>0&&c===0)return '<'+sym+'0.01';", "", ["test_admin"]),
    ("money: panel per-token back to per 1,000", "bin/ollama1-admin",
     "'Cost per 1 million tokens: '+money(m.cost_per_1k_tokens*1000,sym)", "'Cost per 1,000 tokens: '+money(m.cost_per_1k_tokens,sym)", ["test_admin"]),
    ("money: cli shows more than cents", "bin/ollama1-power",
     'return "%s%s" % (sym, format(v, ",.2f"))', 'return "%s%s" % (sym, format(v, ",.4f"))', ["test_power"]),
    ("money: cli sub-cent shown as $0.00", "bin/ollama1-power",
     '    if v > 0 and round(v, 2) == 0:\n        return "<%s0.01" % sym\n', "", ["test_power"]),
    ("info: revision table ignored", "lib/o1gpu.py", "        name = AMD_BY_REVISION.get(key)", "        name = None",
     ["test_gpu"]),
    ("sleep: helper ignores busy work", "bin/ollama1-helper", "    reasons = o1sleep.busy_reasons()\n    if reasons:",
     "    reasons = o1sleep.busy_reasons()\n    if False:", ["test_sleep"]),
    ("sleep: panel ignores busy work", "bin/ollama1-admin", "                if reasons:\n                    return 409",
     "                if False:\n                    return 409", ["test_admin"]),
    ("sleep: busy units not matched", "lib/o1sleep.py", "        if any(fnmatch.fnmatchcase(u, pattern) for u in active):",
     "        if False:", ["test_sleep"]),
    ("sleep: setup lock ignored", "lib/o1sleep.py", '    if setup_running(setup_lock):', "    if False:",
     ["test_sleep"]),
    ("sleep: no restart after a bad wake", "lib/o1sleep.py",
     '        restart(["ollama.service", "ollama1-tunnel.service"])', "        pass", ["test_sleep"]),
    ("dash: ASCII mode lets glyphs through", "lib/o1dashui.py", '        if self.glyphs == "ascii":\n            text =',
     '        if False:\n            text =', ["test_dash"]),
    ("dash: pairing overlay not full screen", "lib/o1dashui.py",
     '    for yy in range(c.h):\n        c.put(0, yy, " " * c.w, "overlay")', "    pass", ["test_dash"]),
    ("dash: no clipping at the edge", "lib/o1dashui.py", "            if 0 <= xi < self.w:", "            if 0 <= xi:",
     ["test_dash"]),
    ("dash: partitions counted twice", "lib/o1metrics.py",
     'DISK_RE = re.compile(r"^(nvme\\d+n\\d+|sd[a-z]+|vd[a-z]+|hd[a-z]+)$")',
     'DISK_RE = re.compile(r"^(nvme\\d+n\\d+\\S*|sd[a-z]+\\d*|vd[a-z]+|hd[a-z]+)$")', ["test_dash"]),
    ("dash: idle time ignored", "lib/o1metrics.py", "        idle = vals[3] + (vals[4] if len(vals) > 4 else 0)",
     "        idle = 0", ["test_dash"]),
    ("dash: braille without the glyphs", "lib/o1font.py",
     '    if blocks and all(ord(c) in cps for c in NEEDED["braille"]):', "    if blocks:", ["test_dash"]),
    ("setup: no mkfs after a crash before it", "lib/setuplib.sh",
     "    run mkfs.ext4 -F -q -L o1data", "    true && : mkfs.ext4 -F -q -L o1data", ["test_setuplib"]),
    ("setup: array mkfs without setup's marker", "lib/setuplib.sh",
     '    [ -f "$STATE_DIR/raid.mkfs-pending" ] || fsck_hint', "    true || fsck_hint", ["test_setuplib"]),
    ("setup: models mkfs without setup's marker", "lib/setuplib.sh",
     '    [ -f "$STATE_DIR/models.mkfs-pending" ] || fsck_hint', "    true || fsck_hint", ["test_setuplib"]),
    ("setup: blkid read errors ignored", "lib/setuplib.sh",
     '    *) echo "blkid could not read $1 (exit $rc)" >&2; return 3 ;;', "    *) ;;", ["test_setuplib"]),
    ("KV: device switch fails open", "bin/ollama1-gateway", "        if not cleared:", "        if False:",
     ["test_gateway"]),
    ("cf: foreign CNAME changed", "bin/ollama1-cf-access", "        if foreign:", "        if False:",
     ["test_cloudflare"]),
    ("cf: redirects followed", "bin/ollama1-cf-access", "OPENER = urllib.request.build_opener(NoRedirect)",
     "OPENER = urllib.request.build_opener()", ["test_cloudflare"]),
    ("cf: new secret shown only at the end", "bin/ollama1-cf-access",
     '        say("created service token %s (never expires)" % TOKEN_NAME)\n'
     '        if show_secret(tok["client_id"], tok.get("client_secret"), test_mode):',
     '        say("created service token %s (never expires)" % TOKEN_NAME)\n'
     '        if False:', ["test_cloudflare"]),
    ("cf: unshown secret not replaced", "bin/ollama1-cf-access",
     "            rotate = True\n        if rotate is None:", "            pass\n        if rotate is None:",
     ["test_cloudflare"]),
    ("cf: service token expires in a year", "bin/ollama1-cf-access", '"duration": "forever"',
     '"duration": "8760h"', ["test_cloudflare"]),
    ("setup: a mirror on the disks is wiped again", "lib/setuplib.sh",
     '      [ -n "$line" ] && md_line_is_ours "$line" && echo "$dev"', "      true", ["test_setuplib"]),
    ("setup: fstab line without a UUID", [
        ("lib/setuplib.sh", '  [[ "$line" =~ ^UUID=[0-9A-Fa-f-]{8,}[[:space:]] ]] || die', "  true || die"),
        ("lib/setuplib.sh", '  [ -n "$uuid" ] || die "no filesystem UUID on $md; fstab left as it was"', "  true")],
     ["test_setuplib"]),
    ("setup: unparseable free space accepted", "lib/setuplib.sh",
     "  case \"$n\" in ''|*[!0-9]*) return 1 ;; esac", "  true", ["test_setuplib"]),
    ("setup: unexpected signature wiped", "lib/setuplib.sh",
     """    case " $* " in *" $t "*) ;; *) echo "$dev carries '$t'"; bad=1 ;; esac""",
     """    case " $* " in *) ;; esac""", ["test_setuplib"]),
    ("setup: fstab/crypttab/swap users ignored", "lib/setuplib.sh", "  return $found", "  return 1",
     ["test_setuplib"]),
    ("setup: wrong serial wiped", "lib/setuplib.sh",
     '    serial_is "$d2" "$s2" || die', '    true || die', ["test_setuplib"]),
    ("stateless: request body written to disk", "bin/ollama1-gateway",
     "            name, entry = gw.local_model(obj.get(\"model\"))\n",
     "            name, entry = gw.local_model(obj.get(\"model\"))\n"
     "            open(os.path.join(Paths.gw_state, 'last.json'), 'w').write(json.dumps(obj))\n",
     ["test_stateless"]),
    ("stateless: answer logged", "bin/ollama1-gateway",
     "                    self.chunk(line)\n",
     "                    self.chunk(line)\n                    log(\"debug\", reason=line)\n",
     ["test_stateless"]),
    ("stateless: default request log back on", "bin/ollama1-gateway",
     "        def log_message(self, fmt, *args):  # the default logs request lines; we log our own\n            pass",
     "        def log_message(self, fmt, *args):  # the default logs request lines; we log our own\n"
     "            BaseHTTPRequestHandler.log_message(self, fmt, *args)",
     ["test_stateless"]),
    ("admin: any Access user accepted", "bin/ollama1-admin",
     "if not email or not hmac.compare_digest(email.encode(), want.encode()):", "if not email:",
     ["test_admin"]),
    ("admin: CSRF token not checked", "bin/ollama1-admin",
     "if not hmac.compare_digest(tok.encode(), self.csrf(email).encode()):", "if False:", ["test_admin"]),
    ("admin: Origin not checked", "bin/ollama1-admin",
     'if (headers.get("Origin") or "").lower() != self.origin:', "if False:", ["test_admin"]),
    ("admin: pull beyond the allow-list", "bin/ollama1-admin", "if arg not in allowed:", "if False:",
     ["test_admin"]),
    ("admin: reboot without confirmation", "bin/ollama1-admin",
     'if act == "reboot" and obj.get("confirm") != "reboot":', "if False:", ["test_admin"]),
    ("updater: checksum ignored", "bin/ollama1-update-ollama", "if got != want:", "if False:", ["test_updater"]),
    ("updater: GitHub digest ignored", "bin/ollama1-update-ollama",
     'if gh and gh != "sha256:" + want:', "if False:", ["test_updater"]),
    ("updater: archive paths trusted", "bin/ollama1-update-ollama",
     'tf.extractall(dest, filter="data")', 'tf.extractall(dest, filter="fully_trusted")', ["test_updater"]),
    ("updater: missing checksum line accepted", "bin/ollama1-update-ollama",
     "            if not want:\n", "            if False:\n", ["test_updater"]),
    ("cf: duplicate CNAMEs kept", "bin/ollama1-cf-access", "        for r in extra:", "        for r in []:",
     ["test_cloudflare"]),
    ("cf: a new CNAME on every run", "bin/ollama1-cf-access", "        if not cnames:", "        if True:",
     ["test_cloudflare"]),
    ("cf: API token saved to disk", "bin/ollama1-cf-access", "    del token\n",
     "    open(os.path.join(Paths.etc, 'cf-token'), 'w').write(token)\n    del token\n", ["test_cloudflare"]),
    ("cf: tunnel credential readable by all", "bin/ollama1-cf-access",
     "write_json_atomic(creds_path, creds, mode=0o600)", "write_json_atomic(creds_path, creds, mode=0o644)",
     ["test_cloudflare"]),
    ("cf: a new tunnel on every run", "bin/ollama1-cf-access", "    if found:\n", "    if False:\n",
     ["test_cloudflare"]),
    ("library: listed models removed", "lib/o1library.py",
     '        if not kept(m["name"], allowed, protected):', "        if True:", ["test_library"]),
    ("library: removal not re-checked at sync time", "lib/o1library.py",
     "        if list_broken or kept(name, allowed, protected):   # back on the list (or a bad line names it): keep it",
     "        if False:",
     ["test_library"]),
    ("library: delisted model still fetched", "lib/o1library.py",
     '        if listed(item["name"], allowed):', "        if True:", ["test_library"]),
    ("library: update check inverted", "lib/o1library.py",
     'elif str(local.get("digest") or "").replace("sha256:", "") != digest:',
     'elif str(local.get("digest") or "").replace("sha256:", "") == digest:', ["test_library"]),
    ("library: sizes count layers already on disk", "lib/o1library.py",
     "if not have_blob(d))", "if True)", ["test_library"]),
    ("library: only two tries", "lib/o1library.py",
     "for attempt in range(1, tries + 1):", "for attempt in range(1, tries):", ["test_library"]),
    ("library: cached layers counted as progress", "lib/o1library.py",
     'seen[d] = {"cached": done >= tot,', 'seen[d] = {"cached": False,', ["test_library"]),
    ("library: rate not smoothed", "lib/o1library.py",
     "0.85 * self.rate + 0.15 * inst", "inst", ["test_library"]),
    ("library: registry down means remove", "lib/o1library.py",
     "        if manifest is None:\n            if local is None:",
     "        if manifest is None and False:\n            if local is None:", ["test_library"]),
    ("library: bad allow-list line left behind", "lib/o1library.py",
     "        _write_allow(lines[:-1], allow_path)\n", "        pass\n", ["test_library"]),
    ("library: panel sync ignores the preview", "bin/ollama1-models",
     'if want is None or want["id"] != p["id"]:', "if False:", ["test_library"]),
    ("library: sync without typed yes", "bin/ollama1-models",
     'if ask("Type yes to do exactly this: ") != "yes":', "if False:", ["test_library"]),
    ("library: two syncs at once", "lib/o1library.py",
     "            fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)\n", "            pass\n", ["test_library"]),
    ("library: sleep ignores a CLI sync", "lib/o1sleep.py",
     "if lib_why not in reasons and setup_running(library_lock()):", "if False:", ["test_library"]),
    ("admin: library sync without the shown preview", "bin/ollama1-admin",
     'if arg != p["id"] or confirm != p["id"]:', "if False:", ["test_admin"]),
    ("admin: library sync with a stale preview", "lib/o1library.py",
     'if (now or time.time()) - int(p.get("made_at") or 0) > max_age:', "if False:", ["test_admin"]),
    ("admin: library sync without space", "bin/ollama1-admin",
     'if not p.get("enough_space", False):', "if False:", ["test_admin"]),
    ("power: weekends get on-peak", "lib/o1tariff.py",
     'if w["tier"] in ("on", "mid") and self.weekend_like(d):', "if False:", ["test_power"]),
    ("power: holidays ignored", "lib/o1tariff.py",
     'return (self.s["weekends_off_peak"] and d.weekday() >= 5) or self.holiday(d) is not None',
     'return (self.s["weekends_off_peak"] and d.weekday() >= 5)', ["test_power"]),
    ("power: holidays never observed", "lib/o1tariff.py",
     "d = _observed(d) if observed else d", "d = d", ["test_power"]),
    ("power: windows stop at midnight", "lib/o1tariff.py",
     "                elif wraps:\n                    span = range(0, e0)",
     "                elif False:\n                    span = range(0, e0)", ["test_power"]),
    ("power: last window wins, not the most specific", "lib/o1tariff.py",
     "if best[i] is None or key < best[i][0]:", "if True:", ["test_power"]),
    ("power: seasons can't wrap the new year", "lib/o1tariff.py",
     "if (a <= doy <= b) if a <= b else (doy >= a or doy <= b):", "if a <= doy <= b:", ["test_power"]),
    ("power: DST ignored in the fast path", "lib/o1tariff.py",
     "base = lt if end.utcoffset() == lt.utcoffset() else None", "base = lt", ["test_power"]),
    ("power: uncovered time on-peak", "lib/o1tariff.py",
     'm = [b[1] if b else "off" for b in best]', 'm = [b[1] if b else "on" for b in best]', ["test_power"]),
    ("power: time-of-use without prices", "lib/o1tariff.py",
     '            if out["tiers"].get(t) is None:', "            if False:", ["test_power", "test_admin"]),
    ("power: overlapping seasons accepted", "lib/o1tariff.py",
     "                if doy in owner:", "                if False:", ["test_power"]),
    ("power: energy not split at the minute", "lib/o1power.py",
     "            e = min(t1, m + 60)", "            e = t1", ["test_power"]),
    ("power: gaps counted", "lib/o1power.py",
     "            if now - t0 <= GAP_S:", "            if True:", ["test_power"]),
    ("power: sleep not counted", "lib/o1power.py",
     '        self.meter.add(max(t0, a), min(t1, b), float(self.cfg.get("power_sleep_w", 3)), "sleep")',
     "        pass", ["test_power"]),
    ("power: RAPL wrap lost", "lib/o1power.py", "    return (rng - e0) + e1 + 1", "    return 0", ["test_power"]),
    ("power: the plug ignored", "lib/o1power.py", "        if self.plug:\n            try:",
     "        if False:\n            try:", ["test_power"]),
    ("power: plug beyond the LAN", "lib/o1power.py",
     "    if not any(ip in n for n in LAN_NETS if n.version == ip.version):",
     "    if False:", ["test_power"]),
    ("power: plug redirects followed", "lib/o1power.py", "    handlers = [_NoRedirect(), _DeadlineHTTPHandler(deadline)]",
     "    handlers = [_DeadlineHTTPHandler(deadline)]",
     ["test_power"]),
    ("power: unknown time shown as none", "lib/o1power.py",
     '"unknown_h": round(max(0, span - known) / 3600.0, 2)', '"unknown_h": 0', ["test_power"]),
    ("power: one price for a whole window", "lib/o1power.py",
     "    tiers = tariff.tiers_for_minutes([r[0] for r in rows])",
     "    tiers = [tariff.tier_at(rows[0][0])] * len(rows) if rows else []", ["test_power"]),
    ("power: projection ignores the weekday", "lib/o1power.py",
     "        k = lt.weekday() * 24 + lt.hour", "        k = lt.hour", ["test_power"]),
    ("power: Kasa cipher wrong", "lib/o1power.py", "        out.append(key ^ b)\n        key = b",
     "        out.append(key ^ b)\n        key = key ^ b", ["test_power"]),
    ("power: price file readable by all", "lib/o1power.py",
     '    write_json_atomic(tariff_file(), clean, mode=0o640, group="o1view")',
     '    write_json_atomic(tariff_file(), clean, mode=0o644, group="o1view")',
     ["test_power", "test_admin", "test_rootfiles"]),
    ("admin: big bodies on every action", "bin/ollama1-admin",
     '(65536 if path == "/api/power/schedule" else 4096)', "65536", ["test_admin"]),
    ("admin: prices saved unchecked", "bin/ollama1-admin",
     "        clean, errs = o1tariff.validate(obj)\n        if errs:",
     "        clean, errs = obj, []\n        if errs:", ["test_admin"]),
    ("root files: mode set by path", "lib/o1common.py",
     "            os.fchmod(f.fileno(), mode)", "            os.chmod(tmp, mode)", ["test_rootfiles"]),
    ("root files: symlinks followed on read", "lib/o1common.py",
     "os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK", "os.O_RDONLY | os.O_NONBLOCK", ["test_rootfiles"]),
    ("root files: panel request read unsafely", "lib/o1power.py",
     "    s = read_json_safe(path, max_bytes=MAX_SCHEDULE_BYTES,\n"
     "                       check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)",
     "    s = read_json(path)", ["test_rootfiles"]),
    ("root files: tariff read unsafely", "lib/o1power.py",
     "        s = read_json_safe(tariff_file(), max_bytes=MAX_SCHEDULE_BYTES)",
     "        s = read_json(tariff_file())", ["test_rootfiles"]),
    ("root files: pairing spool read unsafely", "lib/o1pair.py",
     "        req = read_json_safe(fp, max_bytes=8192)", "        req = read_json(fp, max_bytes=8192)",
     ["test_rootfiles"]),
    ("power: IPv4-mapped addresses not unwrapped", "lib/o1power.py",
     "    if ip.version == 6 and ip.ipv4_mapped is not None:", "    if False:", ["test_power"]),
    ("power: link-local plugs allowed", "lib/o1power.py",
     '"192.168.0.0/16", "fc00::/7"))', '"192.168.0.0/16", "fc00::/7", "169.254.0.0/16"))',
     ["test_power", "test_rootfiles"]),
    ("power: Shelly Gen1 answers any auth", "lib/o1power.py",
     "        handlers.append(urllib.request.HTTPBasicAuthHandler(mgr) if auth == \"basic\"\n"
     "                        else urllib.request.HTTPDigestAuthHandler(mgr))",
     "        handlers += [urllib.request.HTTPBasicAuthHandler(mgr), urllib.request.HTTPDigestAuthHandler(mgr)]",
     ["test_power"]),
    ("power: any plug error kills the sampler", "lib/o1power.py",
     "            except Exception:\n                self.plug_state = {",
     "            except ZeroDivisionError:\n                self.plug_state = {", ["test_power"]),
    ("power: no overall plug deadline", "lib/o1power.py",
     "        left = self.deadline - time.monotonic()", "        left = PLUG_DEADLINE_S", ["test_power"]),
    ("power: plug reply shape unchecked", "lib/o1power.py",
     "    if not isinstance(v, dict):\n        raise PlugError(\"the %s reply isn't in the expected shape\" % what)",
     "    pass", ["test_power"]),
    ("library: a bad line doesn't protect its model", "lib/o1library.py",
     "    low = [p.lower() for p in protected]\n    return listed(name.lower(), low)",
     "    return False", ["test_library"]),
    ("library: removals planned despite a broken list", "lib/o1library.py",
     '            (blocked if errors else remove).append(', '            remove.append(', ["test_library"]),
    ("library: removals run despite a broken list", "lib/o1library.py",
     "        if list_broken or kept(name, allowed, protected):", "        if kept(name, allowed, protected):",
     ["test_library"]),
    ("library: no disk figure passes", "lib/o1library.py",
     '"enough_space": after is not None and after >= MIN_FREE,', '"enough_space": after is None or after >= MIN_FREE,',
     ["test_library"]),
    ("library: shared blobs counted as freed", "lib/o1library.py",
     "    return sum(s for d, s in gone.items() if d not in keep)", "    return sum(gone.values())",
     ["test_library"]),
    ("library: manifests unchecked", "lib/o1library.py",
     "    if not valid_manifest(m):\n        return None, None", "    if False:\n        return None, None",
     ["test_library"]),
    ("library: registry redirects followed", "lib/o1library.py",
     "    opener = urllib.request.build_opener(_NoRedirect())", "    opener = urllib.request.build_opener()",
     ["test_library"]),
    ("setup-safety: RAM part above MemoryHigh", "bin/ollama1-gateway",
     "            ram_part = min(ram_part, high)", "            ram_part = min(ram_part, cap - (1 << 30)) if cap else ram_part",
     ["test_gateway"]),
    ("setup-safety: inhibitor never let go", "lib/o1sleep.py",
     "                os.killpg(self.p.pid, signal.SIGTERM)", "                pass", ["test_sleep"]),
    ("setup-safety: RAM test ignores a hangup", "tools/ram_model_test.py",
     "    raise SystemExit(128 + signum)", "    return None", ["test_tools"]),
    ("setup-safety: RAM test signals not caught", "tools/ram_model_test.py",
     "        signal.signal(sig, exit_on_signal)", "        pass", ["test_tools"]),
    ("setup-safety: swap off carries on after a failed swapoff", "tools/encrypted-swap.sh",
     '    swapoff "$MAPPER" || die "swapoff $MAPPER failed (not enough free memory to take its pages back?). Nothing was changed; free some memory and try again."',
     '    swapoff "$MAPPER" || true', ["test_tools"]),
    ("setup-safety: swap volume without room", "tools/encrypted-swap.sh",
     '    [ "$free" -ge "$need" ] || die', '    true || die', ["test_tools"]),
    ("setup-safety: swap may hold up the boot", "tools/encrypted-swap.sh",
     "swap,cipher=aes-xts-plain64,size=512,nofail", "swap,cipher=aes-xts-plain64,size=512", ["test_tools"]),
    ("setup-safety: swap not finished on a re-run", "tools/encrypted-swap.sh",
     "  if lv_exists; then\n    echo \"volume $LVDEV: already there\"",
     "  if false; then\n    echo \"volume $LVDEV: already there\"", ["test_tools"]),
    ("setup-safety: swap back in the default RAM test", "tools/ram_model_test.py",
     'DEFAULT_CONFIGS = ["norepack", "norepack-moe"]', 'DEFAULT_CONFIGS = ["norepack", "norepack-moe", "swap"]',
     ["test_tools"]),
    ("setup-safety: swap config runs without the encrypted swap", "tools/ram_model_test.py",
     '    if "swap" not in names or swap_bytes:\n        return None', '    if True:\n        return None',
     ["test_tools"]),
    ("setup-safety: VG reserve not rounded up", "lib/setuplib.sh",
     "  echo $(( (${1:-0} * 1073741824 + e - 1) / e ))", "  echo $(( ${1:-0} * 1073741824 / e ))",
     ["test_setuplib"]),
    ("lows: request owner not checked", "lib/o1power.py",
     "check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)", "check=lambda st: st.st_nlink == 1)",
     ["test_rootfiles"]),
    ("lows: hard-linked request trusted", "lib/o1power.py",
     "check=lambda st: st.st_nlink == 1 and st.st_uid == owner_uid)", "check=lambda st: st.st_uid == owner_uid)",
     ["test_rootfiles"]),
    ("lows: validation echoes an input key", "lib/o1tariff.py",
     '(k if re.match(r"^[a-z_]{1,30}$", str(k)) else "(unreadable name)")', "k", ["test_rootfiles"]),
    ("lows: missing allow-list reads as empty and clean", "lib/o1common.py",
     '        errors.append({"line": 0, "text": "", "reason": "models.allow is missing or can\'t be read"})\n',
     "", ["test_library"]),
    ("lows: freed counted despite an unreadable kept manifest", "lib/o1library.py",
     "            if not isinstance(m, dict):\n                return 0", "            if not isinstance(m, dict):\n                continue",
     ["test_library"]),
    ("lows: CLI inhibitor outlives a killed job", "lib/o1sleep.py",
     '"--why=" + self.why, "sh", "-c", "cat >/dev/null"]', '"--why=" + self.why, "sh", "-c", "sleep 600"]',
     ["test_sleep"]),
    ("lows: setup inhibitor outlives setup", "lib/setuplib.sh",
     "sh -c 'while kill -0 \"$1\" 2>/dev/null; do sleep 2; done'", "sh -c 'while true; do sleep 2; done'",
     ["test_sleep"]),
    ("lows: swap off removes a volume it didn't make", "tools/encrypted-swap.sh",
     "  if state_has lv_created && lv_exists; then", "  if lv_exists; then", ["test_tools"]),
    ("lows: RAM test output can stop the cleanup", "tools/ram_model_test.py",
     "    except (OSError, ValueError):    # BrokenPipeError is an OSError", "    except ValueError:", ["test_tools"]),
    ("usage: the asking device's id served too", "bin/ollama1-gateway",
     '            if method == "GET" and route == "/v1/usage":\n                return self.send_json(200, gw.usage())',
     '            if method == "GET" and route == "/v1/usage":\n                return self.send_json(200, dict(gw.usage(), who=dev_id))',
     ["test_gateway"]),
    ("usage: whatever the reader returns is served", "bin/ollama1-gateway",
     '            return {"gpu": {k: self.usage_val.get(k) for k in USAGE_KEYS},', '            return {"gpu": dict(self.usage_val),',
     ["test_gateway"]),
    ("usage: memory in use taken from MemFree", "lib/o1stats.py",
     '            out["used_bytes"] = total - avail', '            out["used_bytes"] = total - info.get("MemFree", 0)', ["test_gpu", "test_gateway"]),
    ("usage: memory in use above the total served", "lib/o1stats.py",
     "if isinstance(avail, int) and 0 <= avail <= total:", "if isinstance(avail, int):", ["test_gpu"]),
    ("usage: memory not served", "bin/ollama1-gateway",
     '                    "ram": dict(self.ram_val)}', '                    }', ["test_gateway"]),
    ('idle: off still sleeps', 'lib/o1idle.py',
     'if i.get("enabled") is not True:',
     'if False:',
     ['test_idle']),
    ('idle: unsupported still sleeps', 'lib/o1idle.py',
     'if i.get("supported") is not True:',
     'if False:',
     ['test_idle']),
    ('idle: a logged-in session ignored', 'lib/o1idle.py',
     'if i["sessions"] > 0:',
     'if False:',
     ['test_idle']),
    ('idle: unknown sessions guessed', 'lib/o1idle.py',
     'if i.get("sessions") is None:',
     'if False:',
     ['test_idle']),
    ('idle: a request in flight ignored', 'lib/o1idle.py',
     'if i.get("inflight") is None or i["inflight"] > 0:',
     'if False:',
     ['test_idle']),
    ('idle: a running download ignored', 'lib/o1idle.py',
     'if i["busy"]:',
     'if False:',
     ['test_idle']),
    ('idle: a running test or update ignored', 'lib/o1idle.py',
     'if i["tools"]:',
     'if False:',
     ['test_idle']),
    ('idle: a blocking inhibitor ignored', 'lib/o1idle.py',
     'if i["inhibitors"]:',
     'if False:',
     ['test_idle']),
    ('idle: a busy graphics card ignored', 'lib/o1idle.py',
     'if g is not None and g >= GPU_IDLE_PCT:',
     'if False:',
     ['test_idle']),
    ('idle: the graphics threshold off by one', 'lib/o1idle.py',
     'g >= GPU_IDLE_PCT',
     'g > GPU_IDLE_PCT',
     ['test_idle']),
    ('idle: boot time ignored', 'lib/o1idle.py',
     'since = max(last, float(i.get("boot_time") or 0), float(i.get("last_resume") or 0))',
     'since = max(last, float(i.get("last_resume") or 0))',
     ['test_idle']),
    ('idle: a resume ignored', 'lib/o1idle.py',
     'since = max(last, float(i.get("boot_time") or 0), float(i.get("last_resume") or 0))',
     'since = max(last, float(i.get("boot_time") or 0))',
     ['test_idle']),
    ('idle: minutes not clamped', 'lib/o1idle.py',
     'minutes = clamp_minutes(minutes)\n        now',
     'minutes = minutes\n        now',
     ['test_idle']),
    ('idle: a bool taken as minutes', 'lib/o1idle.py',
     'if not _int(minutes):',
     'if False:',
     ['test_idle']),
    ("idle: sleeps at the threshold's edge", 'lib/o1idle.py',
     'if idle < minutes * 60:',
     'if idle <= minutes * 60:',
     ['test_idle']),
    ('idle: a resume not noticed', 'lib/o1idle.py',
     '> RESUME_JUMP_S:',
     '> 10 ** 9:',
     ['test_idle']),
    ('idle: a refused sleep tried again at once', 'lib/o1idle.py',
     'self.retry_at = self.mono() + RETRY_AFTER_REFUSED_S',
     'self.retry_at = 0',
     ['test_idle']),
    ('idle: a probe that fails reads as nothing running', 'lib/o1idle.py',
     '        except Exception:\n            return None\n\n    def tick',
     '        except Exception:\n            return []\n\n    def tick',
     ['test_idle']),
    ('idle: any mem_sleep is deep', 'lib/o1idle.py',
     'return "deep" in words',
     'return True',
     ['test_idle']),
    ('config: a bool taken as a number', 'lib/o1idle.py',
     'return isinstance(v, int) and not isinstance(v, bool)',
     'return isinstance(v, int)',
     ['test_idle']),
    ('config: enabled by anything truthy', 'lib/o1idle.py',
     '"enabled": obj.get("enabled") is True,',
     '"enabled": bool(obj.get("enabled")),',
     ['test_idle']),
    ('config: minutes not clamped on a change', 'lib/o1idle.py',
     'out["minutes"] = clamp_minutes(obj["minutes"])',
     'out["minutes"] = obj["minutes"]',
     ['test_idle']),
    ('config: other keys accepted', 'lib/o1idle.py',
     'if set(obj) - {"enabled", "minutes"}:',
     'if False:',
     ['test_idle']),
    ("activity: a stale file's requests trusted", 'lib/o1idle.py',
     '"inflight": inflight if fresh else 0',
     '"inflight": inflight',
     ['test_idle']),
    ('activity: a request ending below zero', 'lib/o1idle.py',
     'self.inflight = max(0, self.inflight - 1)',
     'self.inflight -= 1',
     ['test_idle']),
    ('probes: a delay lock blocks sleep', 'lib/o1idle.py',
     'if len(t) < 6 or t[-1] != "block":',
     'if len(t) < 6:',
     ['test_idle']),
    ("probes: a lock that isn't about sleep blocks it", 'lib/o1idle.py',
     'if any(re.fullmatch(',
     'if True or any(re.fullmatch(',
     ['test_idle']),
    ('probes: a later argument names a tool', 'lib/o1idle.py',
     'for a in argv[:2]:',
     'for a in argv:',
     ['test_idle']),
    ('wake: virtual cards included', 'lib/o1idle.py',
     'if VIRTUAL_NICS.match(n) or not os.path.exists(os.path.join(d, "device")):',
     'if not os.path.exists(os.path.join(d, "device")):',
     ['test_idle']),
    ('wake: bridges and veths included', 'lib/o1idle.py',
     'if VIRTUAL_NICS.match(n) or not os.path.exists(os.path.join(d, "device")):',
     'if VIRTUAL_NICS.match(n):',
     ['test_idle']),
    ("wake: a card that can't wake is set up", 'lib/o1idle.py',
     'sup = "g" in s.split(":", 1)[1]',
     'sup = True',
     ['test_idle']),
    ('wake: the link file says something else', 'lib/o1idle.py',
     'WakeOnLan=magic',
     'WakeOnLan=phy',
     ['test_idle']),
    ('wake: the link file rewritten every run', 'lib/o1idle.py',
     'if have != want:',
     'if True:',
     ['test_idle']),
    ('wake: more cards than the cap', 'lib/o1idle.py',
     'return out[:MAX_WAKE]',
     'return out',
     ['test_idle']),
    ('wake: junk published as a card', 'lib/o1idle.py',
     'if isinstance(m, str) and MAC_RX.match(m)',
     'if True',
     ['test_idle']),
    ('gateway: a poll counts as activity', 'bin/ollama1-gateway',
     'return self.send_json(200, gw.sleep_view())',
     'gw.activity.begin()\n                return self.send_json(200, gw.sleep_view())',
     ['test_gateway']),
    ('gateway: a finished request still counts as running', 'bin/ollama1-gateway',
     '                finally:\n                    gw.activity.end()',
     '                finally:\n                    pass',
     ['test_gateway']),
    ('gateway: a bad sleep setting accepted', 'bin/ollama1-gateway',
     'raise GatewayError(400, "bad_request", err)',
     'changes = {}',
     ['test_gateway']),
    ("usage: reading not cached", "bin/ollama1-gateway",
     "if self.usage_at is None or now - self.usage_at >= USAGE_CACHE_S:", "if True:", ["test_gateway"]),
    ("usage: a hardware serial served too", "lib/o1gpu.py",
     '    out = {"busy_pct": None, "vram_used_bytes": None, "vram_total_bytes": None}\n    try:\n        if vendor == "amd":',
     '    out = {"busy_pct": None, "vram_used_bytes": None, "vram_total_bytes": None, "serial": _read(_sys() + "/class/drm/card0/device/serial_number")}\n    try:\n        if vendor == "amd":',
     ["test_gpu"]),
    ("usage: a missing file raises", "lib/o1gpu.py",
     'out["busy_pct"] = _pct(_read(dev + "/gpu_busy_percent"))',
     'out["busy_pct"] = _pct(open(dev + "/gpu_busy_percent").read())', ["test_gpu", "test_gateway"]),
    ("usage: out-of-range busy percent served", "lib/o1gpu.py",
     "    return v if 0 <= v <= 100 else None", "    return v", ["test_gpu"]),
    ("step3: reserve ignored when growing /", "lib/setuplib.sh",
     'run lvextend -r -l "+$((free - keep))" /dev/ubuntu-vg/ubuntu-lv', 'run lvextend -r -l "+$free" /dev/ubuntu-vg/ubuntu-lv',
     ["test_setuplib"]),
    ("step3: result of lvextend not checked", "lib/setuplib.sh",
     '    [ "$free" = "$keep" ] || die', "    true || die", ["test_setuplib"]),
    ("step3: grows even at the reserve", "lib/setuplib.sh",
     '  if [ "$free" -gt "$keep" ]; then', '  if [ "$free" -ge "$keep" ]; then', ["test_setuplib"]),
]


def main():
    only = sys.argv[1] if len(sys.argv) > 1 else ""
    survived = []
    ran = 0
    for m in MUTANTS:
        if len(m) == 3:
            name, rel, tests = m
            old = new = None
        else:
            name, rel, old, new, tests = m
        if only and only not in name:
            continue
        ran += 1
        work = tempfile.mkdtemp(prefix="o1mut-")
        try:
            for d in ("lib", "bin", "config", "systemd", "tools"):
                shutil.copytree(os.path.join(KIT, d), os.path.join(work, d))
            edits = rel if isinstance(rel, list) else [(rel, old, new)]
            broken = False
            for erel, eold, enew in edits:
                path = os.path.join(work, erel)
                src = open(path).read()
                if src.count(eold) != 1:
                    print("BROKEN  %-50s  (the original text appears %d times)" % (name, src.count(eold)))
                    broken = True
                    break
                open(path, "w").write(src.replace(eold, enew))
            if broken:
                survived.append(name)
                continue
            env = dict(os.environ, OLLAMA1_TEST_LIB=os.path.join(work, "lib"),
                       OLLAMA1_TEST_BIN=os.path.join(work, "bin"), OLLAMA1_TEST_TOOLS=os.path.join(work, "tools"),
                       PYTHONWARNINGS="ignore")
            env.pop("OLLAMA1_PREFIX", None)
            try:
                r = subprocess.run([sys.executable, "-m", "unittest"] + tests, cwd=HERE, env=env,
                                   capture_output=True, text=True, timeout=300)
            except subprocess.TimeoutExpired:
                # e.g. root blocking on a planted FIFO: the tests hang instead of passing
                print("killed  %s  (the tests hung)" % name)
                continue
            if r.returncode == 0:
                print("SURVIVED %-50s  (%s still pass)" % (name, " ".join(tests)))
                survived.append(name)
            else:
                print("killed  %s" % name)
        finally:
            shutil.rmtree(work, ignore_errors=True)
    print("\n%d mutants, %d killed, %d survived" % (ran, ran - len(survived), len(survived)))
    return 1 if survived else 0


if __name__ == "__main__":
    sys.exit(main())
